- Sources/AppcuesKit/Data/Analytics/Storage/ActivityFileStorage.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesSkippableTrait.swift
- Tests/AppcuesKitTests/Actions/ActionRegistryTests.swift
- Tests/AppcuesKitTests/Actions/AppcuesCloseActionTests.swift
- Tests/AppcuesKitTests/Actions/AppcuesContinueActionTests.swift
- Tests/AppcuesKitTests/Actions/AppcuesLaunchExperienceActionTests.swift
- Tests/AppcuesKitTests/Actions/AppcuesLinkActionTests.swift
- Tests/AppcuesKitTests/Actions/AppcuesTrackActionTests.swift
- Tests/AppcuesKitTests/Actions/AppcuesUpdateProfileActionTests.swift
- Tests/AppcuesKitTests/DeeplinkHandlerTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceLoaderTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceRendererTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceStateMachine+AnalyticsObserverTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceStateMachineTests.swift
- Tests/AppcuesKitTests/MockAppcues.swift
- Tests/AppcuesKitTests/Mocks.swift
- Tests/AppcuesKitTests/Networking/DynamicCodingKeysTests.swift
- Tests/AppcuesKitTests/Networking/PartialDictionaryDecodeTests.swift
- Tests/AppcuesKitTests/Traits/TraitComposerTests.swift
- Tests/AppcuesKitTests/Traits/TraitRegistryTests.swift
Swift Package Index builds [failed](https://swiftpackageindex.com/builds/DA22ED22-09EA-4C08-A500-805CCBA2A37F) because of missing version checks in the tests. Add those checks so that things will compile properly.
Also made the one line change to ActivityFileStorage that makes it compile for Swift 4.2, because why not, and added the accessibility label to the skip button that the UI tests look for.
> Add version checks to tests

- Appcues.podspec
- Package.swift
- README.md
- Sources/AppcuesKit/Appcues+Config.swift
- Sources/AppcuesKit/Presentation/Actions/Appcues/AppcuesCloseAction.swift
- Sources/AppcuesKit/Presentation/DeeplinkHandler.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine.swift
- Sources/AppcuesKit/Presentation/Generated/Appcues+ResourceBundle.swift
- 🚨 Fix lint warnings
- 📝 Fix documentation error
- Helpfully enough, the objc interface flagged the wrong param name
- 📝 Add XCFramework installation instructions
- 🍏 Clean up podspec
- 🍏 Update swift tools version
- This shouldn't matter at all, but a bit more backwards compatibility can't hurt
- 🐛 Fix bundle referencing from XCFramework
- The `1.0.0-beta.1` XCFramework couldn't find the debug icon
- 📝 Update README image path to fix display outside of github
- This should fix the broken image on the [CocoaPods listing](https://cocoapods.org/pods/Appcues)
> Misc touchups

- Sources/AppcuesKit/Data/Analytics/AnalyticsPublisher.swift
- Sources/AppcuesKit/Presentation/Debugger/UIDebugger.swift
- Tests/AppcuesKitTests/Analytics/AnalyticsPublisherTests.swift
A follow up to https://github.com/appcues/appcues-ios-sdk/pull/203
Updated dependency graph changes to the lines in/out of `AnalyticsPublishing`:
|Now|Before|
|-|-|
|![dependency-graph](https://user-images.githubusercontent.com/845681/172225955-2db744b6-d564-4fa9-96fe-313b7d3042ef.png)|![depencency-graph-old](https://user-images.githubusercontent.com/845681/172225965-04e36173-4031-4165-84b0-d5af32c1622b.png)|
> Update AnalyticsPublisher to weakly reference decorators and subscribers

- .spi.yml
Trying this before opening an issue for the [missing docs](https://swiftpackageindex.com/appcues/appcues-ios-sdk/main/documentation/appcueskit) on the Swift Package Index.
The xcodebuild command for docs requires the _scheme_ not a target, so perhaps that's what's wrong
```sh
$ xcodebuild docbuild -scheme Appcues -sdk iphoneos -destination generic/platform=iOS
```
> Update SPI doc target

- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesCarouselTrait.swift
- Sources/AppcuesKit/Presentation/UI/ExperienceStepViewController.swift
It was terribly broken. Now it's not. Not a whole lot more to say than that.
I will says overriding `safeAreaInsets` is hacky, but for the life of me I can't figure out why the safe area is double applied. The middle video shows what was happening: the first page looks fine, but as you scroll, the safe area gets doubled on one side. Which side gets the extra space depends which direction you're scrolling, which is extra weird. Because we're using the compositional collection view layout, there's not any visibility into how that's being calculated.
https://user-images.githubusercontent.com/845681/174891845-fb2483b6-75e1-4440-ac0b-fcbff9ed32ac.mp4
https://user-images.githubusercontent.com/845681/174892757-bdd9fa29-9ba2-45e1-afef-4f13f9ac94c5.mp4 …
> Fix fullscreen landscape carousel

- Sources/AppcuesKit/Presentation/Extensions/NSCollectionLayoutSection+Factory.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesCarouselTrait.swift
- Sources/AppcuesKit/Presentation/UI/ExperienceStepViewController.swift
In some cases a carousel modal would end up on a different page after rotating the device. This is a bug with `UICollectionViewCompositionalLayout`. Apple's example code for [Implementing Modern Collection Views](https://developer.apple.com/documentation/uikit/views_and_controls/collection_views/implementing_modern_collection_views) also includes this bug where the items in view when in portrait are lost and different items end up being visible. See this example where item 3,9 is visible in portrait, but 3,3 ends up visible after rotation (not to mention losing the vertical scroll position too)
https://user-images.githubusercontent.com/845681/175646186-a2868c81-e89a-448c-9633-9d5751d3911a.mp4
In theory fixing this should be done with …
> Ensure the same carousel step is always shown on orientation changes

- Sources/AppcuesKit/Presentation/Debugger/Panel/DebugViewModel.swift
When launched, dismissed, relaunched, the current user would be empty
> 🐛 Fix debugger clearing current user value

- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceRenderer.swift
- Tests/AppcuesKitTests/Experiences/ExperienceRendererTests.swift
- Tests/AppcuesKitTests/Mocks.swift
From [sc-38212: iOS SDK doesn't update property from button action](https://app.shortcut.com/appcues/story/38212/mobile-ios-sdk-doesn-t-update-property-from-button-action):
> It appears that this is an issue only on the last step of an experience. The profile details are successfully updated if the action is on the first step of a two step experience.
> The issue stems from sc-37520. The first action on the button is `@appcues/continue` and that tells the SDK "go to the next step, and once we're there, continue on to any additional actions". However, if the experience dismisses, we never see another step so the `@appcues/continue` action doesn't complete and we just wait forever to get to the `@appcues/update-profile` action.
> To summarize, the issue is actually with `@appcues/continue`, …
> Ensure the completion block is called when continue from the last step

- Sources/AppcuesKit/Presentation/Extensions/View+Appcues.swift
I realized I overlooked ensuring buttons actions works with VoiceOver and Voice Control. No more!
(AFAIK SwiftUI automatically makes accessibility actions work with button actions, but since we have the `simultaneousGesture` workaround, we need to be explicit.)
> Add support for accessibility actions on buttons

- Sources/AppcuesKit/Data/Models/Experience.swift
- Sources/AppcuesKit/Presentation/Actions/ActionRegistry.swift
- Sources/AppcuesKit/Presentation/Actions/Appcues/AppcuesLaunchExperienceAction.swift
- Sources/AppcuesKit/Presentation/Actions/Appcues/AppcuesLinkAction.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine+State.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateObserver.swift
- Sources/AppcuesKit/Presentation/Extensions/View+Appcues.swift
- Sources/AppcuesKit/Presentation/UI/Components/AppcuesBox.swift
- Sources/AppcuesKit/Presentation/UI/Components/AppcuesButton.swift
- Sources/AppcuesKit/Presentation/UI/Components/AppcuesImage.swift
- Sources/AppcuesKit/Presentation/UI/Components/AppcuesStack.swift
- Sources/AppcuesKit/Presentation/UI/Components/AppcuesText.swift
- Sources/AppcuesKit/Presentation/UI/ExperienceStepViewModel.swift
- Tests/AppcuesKitTests/Actions/ActionRegistryTests.swift
- Tests/AppcuesKitTests/Analytics/ActivityProcessorTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceStateMachineTests.swift
- Tests/AppcuesKitTests/Mocks.swift
- Tests/AppcuesKitTests/Traits/TraitComposerTests.swift
This PR does two things:
1. Update `ActionRegistry` to be have a queue for all experience actions that need to be processed. By itself this changes nothing.
2. Experience actions are now mapped and handled by appending to the `ActionRegistry` queue.
The result of this is that an experience that's dismissed via a button will handle all the button actions in the queue and then the experience actions afterwards. See the example below.
Moving action handling to `ActionRegistry` cleaned up a bunch of messy closure passing that I was doing before and overall it's a substantially cleaner solution.
The experience actions then just need to add to the `ActionRegistry` queue. One approach was to create an `ExperienceStateObserver` and look for the `endingExperience` state, but introducing a new …
> Add centralized action queue and support for post-experience actions

- Sources/AppcuesKit/Presentation/ExperienceLoader.swift
- Sources/AppcuesKit/Presentation/Traits/TraitComposer.swift
- Sources/AppcuesKit/Presentation/UI/ExperienceStepViewController.swift
- Tests/AppcuesKitTests/Experiences/ExperienceLoaderTests.swift
Went with the notification approach since coupling the ExperienceStepViewController to the ExperienceLoader seems like a bad idea.
> Add shake gesture detection to refresh experience previews

- Sources/AppcuesKit/AppcuesKit.docc/Debugging.md
- Sources/AppcuesKit/AppcuesKit.docc/URLSchemeConfiguring.md
- Sources/AppcuesKit/Presentation/Debugger/Panel/DebugViewModel.swift
- Sources/AppcuesKit/Presentation/Debugger/UIDebugger.swift
- Sources/AppcuesKit/Presentation/DeeplinkHandler.swift
- Sources/AppcuesKit/Presentation/UI/ExperienceStepViewModel.swift
- Tests/AppcuesKitTests/DeeplinkHandlerTests.swift
- Tests/AppcuesKitTests/MockAppcues.swift
This was actually quite simple: for the first check we inspect the `Info.plist`, then we call a new deeplink url that doesn't do anything other than tell the debugger that the link was received. There's a unique token for each call just in case there's any weirdness with multiple SDK instances or something like that.
Video here: https://a.cl.ly/12uLZwxl
> Add ability to verify deeplink configuration from within the debugger

- Sources/AppcuesKit/Presentation/Extensions/UIViewController+Embed.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesBackgroundContentTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesCarouselTrait.swift
- Sources/AppcuesKit/Presentation/Traits/DefaultContainerViewController.swift
- Sources/AppcuesKit/Presentation/UI/AppcuesHostingController.swift
- Sources/AppcuesKit/Presentation/UI/DynamicContentSizing.swift
Fix up an issue noticed while testing out embedded content ideas - this should prevent any container sizing from being based upon the preferred size of a background content ViewController (which has height zero).
> Improve support for dynamic content sizing with background content

- Sources/AppcuesKit/Data/Models/Experience/ExperienceComponent.swift
- Sources/AppcuesKit/Presentation/Extensions/Inits/Font+Double.swift
- Sources/AppcuesKit/Presentation/Extensions/View+Appcues.swift
- Sources/AppcuesKit/Presentation/UI/Components/AppcuesOptionSelect.swift
- Sources/AppcuesKit/Presentation/UI/Components/AppcuesTextInput.swift
- Sources/AppcuesKit/Presentation/UI/Components/ExperienceComponent+View.swift
- Sources/AppcuesKit/Presentation/UI/Components/MultilineTextView.swift
- Sources/AppcuesKit/Presentation/UI/Components/SelectToggleView.swift
- Sources/AppcuesKit/Presentation/UI/ExperienceStepViewModel.swift
This PR maps the data models and implements _most_ of the UI functionality.
Currently unimplemented or rough around the edges:
- ~multiline text, max input length~
- keyboard safe area management for the text field
- ~checkbox/radio control styling (json model updates tbd)~
These additional primitives along with their complexity are creating some strange CPU and memory usage issues within SwiftUI. The update to `View+Appcues` wrapping `AnyView` fixes those and doesn't seem to have any other side effects despite `AnyView` generally being an anti-pattern. Definitely something to keep an eye on.
Otherwise, this is actually fairly simple for what it enables. All the form state is stored in the `ExperienceStepViewModel` and so we'll be able to grab the info out of there to send the necessary …
> Add basic UI implementation for form components

- Sources/AppcuesKit/Data/Models/Experience/StepReference.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceRenderer.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine+Action.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine+ExperienceError.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine+State.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/LifecycleEvent.swift
- Sources/AppcuesKit/Presentation/Traits/TraitComposer.swift
- Sources/AppcuesKit/Presentation/UI/Components/AppcuesOptionSelect.swift
- Sources/AppcuesKit/Presentation/UI/Components/AppcuesTextInput.swift
- Sources/AppcuesKit/Presentation/UI/ExperienceData.swift
- Sources/AppcuesKit/Presentation/UI/ExperienceStepRootView.swift
- Sources/AppcuesKit/Presentation/UI/ExperienceStepViewController.swift
- Sources/AppcuesKit/Presentation/UI/ExperienceStepViewModel.swift
- Tests/AppcuesKitTests/Experiences/ExperienceRendererTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceStateMachine+AnalyticsObserverTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceStateMachineTests.swift
- Tests/AppcuesKitTests/Experiences/StepRefTests.swift
- Tests/AppcuesKitTests/MockAppcues.swift
- Tests/AppcuesKitTests/Mocks.swift
- Tests/AppcuesKitTests/Traits/TraitComposerTests.swift
The impetus for this change is to make form state persist across step container presentations.
Storing the form state in the ExperienceStepViewModel obviously doesn't work anymore since that gets created/destroyed with the step group. We need something associated with the Experience itself. The solution is `ExperienceData`, a wrapper class around the `Experience` object that also includes the form state and gets used in the `ExperienceStateMachine`.
1. By using `@dynamicMemberLookup` I was able to limit the refactoring to mostly updating `Experience->ExperienceData` rather than also having to change `experience.id->experience.model.id`.
2. Because `ExperienceData` contains an `ObservableObject`, it has to be iOS 13+, which impacts a couple other spots, but that doesn't matter much.
3. I …
> Add ExperienceData model to wrap Experience object and hold form state

- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine+State.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateObserver.swift
- Tests/AppcuesKitTests/Experiences/ExperienceStateMachine+AnalyticsObserverTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceStateMachineTests.swift
Then:
https://user-images.githubusercontent.com/845681/191343048-eb96a3c1-62c9-47ca-b1b6-f05939dabb9f.mp4
Now:
https://user-images.githubusercontent.com/845681/191343129-29375418-80b7-4374-af96-c15ea5a31634.mp4
I added a test case for not sending the analytics event, but that doesn't reach all the way into the logic for how `markComplete` is set. Open to ideas there since the state machine tests don't make capturing the intermediate transitions easy.
> Fix step_completed event being improperly triggered

- Sources/AppcuesKit/Data/Networking/DynamicCodingKeys.swift
- Tests/AppcuesKitTests/Networking/DynamicCodingKeysTests.swift
Issue noticed during testing of the Capacitor plugin, as the JS side was passing in a value of `1` that was being serialized as `true` in the resulting network call.  The reason was that it was actually NSNumber(1) and our code was checking if it could be casted to a Bool first, which it could.
This is an example of the same issue, in the native code.  I trigger an event with properties like 
```swift
Appcues.shared.track(
name: "event1",
properties: [
"myInt": NSNumber(1),
"myBool": true
])
```
resulting JSON output before this change:
resulting JSON output after this change:
This also works as expected `"myBool": NSNumber(booleanLiteral: true)` -- output is boolean value in the JSON
> Fix serialization of NSNumber values that are not actually booleans

- Sources/AppcuesKit/Data/Models/Experience/ExperienceComponent.swift
- Sources/AppcuesKit/Presentation/UI/ExperienceData.swift
- Sources/AppcuesKit/Presentation/UI/ExperienceStepViewModel.swift
- Tests/AppcuesKitTests/Experiences/ExperienceDataTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceStateMachine+AnalyticsObserverTests.swift
The tests are lined up with the rules listed in the spec PR: https://github.com/appcues/appcues-mobile-experience-spec/pull/84
This PR also orders the multi select output by the order checked.
> Add support for minimum and maximum option selects

- Sources/AppcuesKit/Presentation/Actions/ActionRegistry.swift
- Sources/AppcuesKit/Presentation/Actions/Appcues/AppcuesSubmitFormAction.swift
- Sources/AppcuesKit/Presentation/Actions/ExperienceActionQueueTransforming.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceRenderer.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine+State.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateObserver.swift
- Sources/AppcuesKit/Presentation/UI/ExperienceData.swift
- Tests/AppcuesKitTests/Actions/ActionRegistryTests.swift
- Tests/AppcuesKitTests/Actions/AppcuesCloseActionTests.swift
- Tests/AppcuesKitTests/Actions/AppcuesSubmitFormActionTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceStateMachine+AnalyticsObserverTests.swift
- Tests/AppcuesKitTests/MockAppcues.swift
- Tests/AppcuesKitTests/Mocks.swift
This PR introduces `ExperienceActionQueueTransforming` which modifies the array of actions triggered by a particular interaction. Any `ExperienceAction` can conform to the protocol and then be given a chance to modify the array of actions from the Experience data model before it gets enqueued to execute. This protocol is currently internal, but could easily be made public if we wanted to allow custom `ExperienceAction` implementations to have this capability (it's super powerful, and therefore super easy to mess things up).
For each action in the original queue, we check if its still in the queue (it could have been removed by a previous action) and we check if it's `ExperienceActionQueueTransforming` and then apply the transformation.
A couple edge cases to note: if the order is changed, …
> Move form submission analytics to @appcues/submit-form action

- Sources/AppcuesKit/Data/Models/Experience/ExperienceComponent.swift
- Sources/AppcuesKit/Presentation/Actions/Appcues/AppcuesSubmitFormAction.swift
- Sources/AppcuesKit/Presentation/UI/Components/AppcuesOptionSelect.swift
- Sources/AppcuesKit/Presentation/UI/Components/AppcuesTextInput.swift
- Sources/AppcuesKit/Presentation/UI/Components/SelectToggleView.swift
- Sources/AppcuesKit/Presentation/UI/Components/TintedTextView.swift
- Sources/AppcuesKit/Presentation/UI/ExperienceData.swift
- Tests/AppcuesKitTests/Actions/AppcuesSubmitFormActionTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceDataTests.swift
- Tests/AppcuesKitTests/Mocks.swift
New `errorLabel` will show when appropriate. The `@appcues/submit-form` action sets `stepState.shouldShowErrors = true` and that is used to show the error states.
I introduced `TintedTextView` which is almost the same as `AppcuesText` but allows overriding the tint color to be set to the error color. It seemed strange to modify `AppcuesText` to support this, hence the new View.
> Add UI for form component error states

- Sources/AppcuesKit/Data/Models/Experience/StepReference.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceRenderer.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine+State.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateObserver.swift
- Tests/AppcuesKitTests/Experiences/ExperienceStateMachine+AnalyticsObserverTests.swift
- Tests/AppcuesKitTests/Experiences/StepRefTests.swift
There's two reasonably simple cases to handle here: swiping backwards in a carousel and a button with a negative offset.
Carousel handling:
https://github.com/appcues/appcues-ios-sdk/blob/ca5561dfe26c19f05f417f3b54fa32769d582017/Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine.swift#L139
Button handling:
https://github.com/appcues/appcues-ios-sdk/blob/ca5561dfe26c19f05f417f3b54fa32769d582017/Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine%2BState.swift#L182-L184
The trickiest part of this was a gross bit of code where we would check `if result.isStepCompleted` instead of the actual value of `markComplete` in the state (see the retro below for how this ended up being gross). This check meant that navigating backwards from the last step …
> Fix step_completed event being improperly triggered on backwards navigation

- Sources/AppcuesKit/Data/Extensions/Sequence+CompactMapFirst.swift
- Sources/AppcuesKit/Data/Models/Experience/ExperienceComponent.swift
- Sources/AppcuesKit/Presentation/Actions/ActionRegistry.swift
- Sources/AppcuesKit/Presentation/Actions/Appcues/AppcuesStepInteractionAction.swift
- Sources/AppcuesKit/Presentation/Actions/MetadataSettingAction.swift
- Sources/AppcuesKit/Presentation/Extensions/View+Appcues.swift
- Sources/AppcuesKit/Presentation/Traits/TraitComposer.swift
- Sources/AppcuesKit/Presentation/UI/Components/AppcuesBox.swift
- Sources/AppcuesKit/Presentation/UI/Components/AppcuesButton.swift
- Sources/AppcuesKit/Presentation/UI/Components/AppcuesImage.swift
- Sources/AppcuesKit/Presentation/UI/Components/AppcuesOptionSelect.swift
- Sources/AppcuesKit/Presentation/UI/Components/AppcuesStack.swift
- Sources/AppcuesKit/Presentation/UI/Components/AppcuesText.swift
- Sources/AppcuesKit/Presentation/UI/Components/AppcuesTextInput.swift
- Sources/AppcuesKit/Presentation/UI/Components/TintedTextView.swift
- Sources/AppcuesKit/Presentation/UI/ExperienceStepViewModel.swift
- Sources/AppcuesKit/Vendor/FLAnimatedImage.swift
- Tests/AppcuesKitTests/Actions/ActionRegistryTests.swift
- Tests/AppcuesKitTests/Actions/StepInteractionActionTests.swift
Whenever a button (or, technically any view with an action) is tapped, we want to record the `step_interaction` event with some metadata about that action.
To do this, we:
1. Look up the tapped element in the JSON model, and get its text description.
2. Try and figure out what the "primary" action is from the queue and fill out a `category` and `destination` value. To do this, the actions we care about conform to the `MetadataSettingAction` protocol. We go backwards through the action queue because that heuristic (currently) gives us the actions we care about with how they're ordered by the mobile builder. This isn't foolproof, but it's *mostly right* (entirely right for the current cases) and that's good enough.
3. Prefix the action queue with a new internal …
> Add step_interaction analytics event for button presses

- Sources/AppcuesKit/Data/Analytics/AnalyticsBroadcaster.swift
- Sources/AppcuesKit/Data/Networking/NetworkClient.swift
- Sources/AppcuesKit/Presentation/UI/ExperienceData.swift
- Tests/AppcuesKitTests/Analytics/AnalyticsBroadcasterTests.swift
- Tests/AppcuesKitTests/Analytics/AnalyticsTrackerTests.swift
This PR converts `Date` objects to milliseconds and `StepState` objects to nested `[String: Any]` primitive JSON-compatible types.
The cool part is unlike the x-platform implementations (eg [React Native](https://github.com/appcues/appcues-react-native-module/blob/15d2d650d1cc812bdab26d5f512c900bbda99172/ios/AppcuesReactNative.swift)), I was able to do it without repeating the `switch` for `Dictionary` and `Array`. It's a bit tricky, and I learned a bunch (thanks to [this discussion](https://forums.swift.org/t/idea-mutatingforeach-for-collections/18442)), but the solution is quite nice.
I updated the tests to handle comparing arrays and the Int64 millisecond value. The `file: StaticString = #file, line: UInt = #line` stuff just makes it easier to understand failures in Xcode.
|Now|Before| …
> Sanitize event properties to known types before broadcasting outside the SDK

- Sources/AppcuesKit/Presentation/Extensions/View+Appcues.swift
The way we're drawing borders (a SwiftUI `RoundedRectangle` overlay) is inconsistent with Android and just plain looked weird. The center of the border line was the edge of the view, so half the border could get cropped out. This fixes things to draw the border entirely within the frame of the view (consistent with Android).
```json
"style": {
"borderWidth": 5,
"borderColor": { "light": "#ff0000" }
}
```
|Fixed|Broken|Android|
|-|-|-|
|![fixed](https://user-images.githubusercontent.com/845681/195435720-18b7db66-242f-43e0-8366-ebb8b51cc651.png)|![broken](https://user-images.githubusercontent.com/845681/195435774-e8ac60cd-37f2-4465-b087-f1daf85b3802.png)|![com appcues host ExperienceTests_testModalOne](https://user-images.githubusercontent.com/845681/195438152-9b754b7d-df74-4a58-b9a4-151eda1 …
> Fix border rendering to be entirely inside the view bounds

- Sources/AppcuesKit/Presentation/Actions/ActionRegistry.swift
Ensures the step_interaction isnt affected by or afffecting the queue transform for the other actions.
Matches the approach @andretortolano proposed in https://github.com/appcues/appcues-android-sdk/pull/248
> Update step_interaction analytic to enqueue separately from Experience actions

- Sources/AppcuesKit/Presentation/UI/Components/AppcuesStack.swift
- Sources/AppcuesKit/Presentation/UI/Components/AppcuesText.swift
- Sources/AppcuesKit/Presentation/UI/Components/EqualWidthStack.swift
_Behold_, after a week of experimenting and testing, a new `EqualWidthStack` component that does what you could do in UIKit with a `UIStackView` and `distribution = .fillEqually`.
Basically we want to measure the width available to the stack and set each the width of each item to `width/items.count`. The comments in the code hopefully explain why it is the way it is.
A few helpful references for posterity:
- https://www.fivestars.blog/articles/swiftui-share-layout-information/
- https://www.fivestars.blog/articles/preferencekey-reduce/
- https://www.swiftbysundell.com/articles/swiftui-layout-system-guide-part-2/#geometry-preferences-and-layout-dependencies
> Fix equal width stack layout

- Sources/AppcuesKit/Appcues.swift
- Sources/AppcuesKit/Data/Analytics/AnalyticsTracker.swift
- Sources/AppcuesKit/Data/Analytics/AutoPropertyDecorator.swift
- Sources/AppcuesKit/Data/Analytics/TrackingUpdate.swift
- Sources/AppcuesKit/Data/Models/Experience/ExperienceComponent.swift
- Sources/AppcuesKit/Presentation/Actions/Appcues/AppcuesSubmitFormAction.swift
- Sources/AppcuesKit/Presentation/UI/ExperienceData.swift
- Tests/AppcuesKitTests/Actions/AppcuesSubmitFormActionTests.swift
- Tests/AppcuesKitTests/Analytics/AnalyticsBroadcasterTests.swift
- Tests/AppcuesKitTests/Analytics/AnalyticsTrackerTests.swift
- Tests/AppcuesKitTests/Analytics/AutoPropertyDecoratorTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceDataTests.swift
- Tests/AppcuesKitTests/Mocks.swift
The main change here is simple, and mostly isolated to just the `ExperienceData` file - where a new `attributeName` is handled, and used in the profile update if present. It adds a second profile attribute, in addition to the default update.
The other changes in the handling of the `.profile` tracking type are from noticing that we were not actually batching the form submit analytics together properly, previously. In the existing code, it would send out three separate requests: a `step_interaction` for the button tap (which had a flushed triggered by next item), a `profile_update` for the attribute which was set to always send immediately, and another `step_interaction` (and maybe more) for the form submit.
These can actually all be grouped together in this case, by allowing the …
> Add support for custom attribute name to store survey question results

- Sources/AppcuesKit/Data/Analytics/AnalyticsTracker.swift
- Sources/AppcuesKit/Data/Models/Experience.swift
- Sources/AppcuesKit/Data/Models/Experiment.swift
- Sources/AppcuesKit/Data/Models/QualifyResponse.swift
- Sources/AppcuesKit/Presentation/ExperienceLoader.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceRenderer.swift
- Sources/AppcuesKit/Presentation/UI/ExperienceData.swift
- Tests/AppcuesKitTests/Analytics/ActivityProcessorTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceLoaderTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceRendererTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceStateMachineTests.swift
- Tests/AppcuesKitTests/MockAppcues.swift
- Tests/AppcuesKitTests/Mocks.swift
- Tests/AppcuesKitTests/Traits/TraitComposerTests.swift
* decode a top level `experiments` mapping on the `QualificationResponse`
* add support for an optional `experiment_id` on `Experience`
* modify `ExperienceRenderer` to support experiment logic, if there is a matching experiment for an `Experience` being rendered:
* if group is `control` - block rendering the experience and move on to next priority, if any
* if not (group `exposed`) - continue rendering the experience as usual
* in both cases, trigger an `appcues:experiment_entered` analytic for the user, with the group and experiment ID
update: to make the `ExperienceRenderer` portion more compact and flexible - it now operates on `ExperienceData` objects passed in, rather than `Experience`.  `ExperienceData` can then expand to contain more metadata about the `Experience`, such as the …
> Add support for experiments

- Sources/AppcuesKit/Data/Analytics/ActivityProcessor.swift
- Sources/AppcuesKit/Data/Analytics/AnalyticsTracker.swift
- Sources/AppcuesKit/Data/Analytics/SessionMonitor.swift
- Sources/AppcuesKit/Data/Analytics/Storage/ActivityFileStorage.swift
- Sources/AppcuesKit/Data/Analytics/Storage/ActivityStorage.swift
- Sources/AppcuesKit/Data/Models/SdkMetrics.swift
- Sources/AppcuesKit/Data/Networking/DynamicCodingKeys.swift
- Sources/AppcuesKit/Data/Networking/NetworkClient.swift
- Sources/AppcuesKit/Presentation/Debugger/Panel/DebugViewModel.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateObserver.swift
- Sources/AppcuesKit/Presentation/UI/ExperienceData.swift
- Tests/AppcuesKitTests/Analytics/ActivityProcessorTests.swift
- Tests/AppcuesKitTests/MockAppcues.swift
- Tests/AppcuesKitTests/Networking/NetworkClientTests.swift
This stacks on #258 , as it builds upon the updates to `ExperienceData` and the usage in `ExperienceRenderer`.
The approach here is a static registry of metrics by request ID - in `SdkMetrics`.  This is where other spots can track key points in the qualification/rendering lifecycle.
* the moment the analytic comes in to the sdk
* when it is sent out in the network request
* when it returns from the network
* when it starts presentation in the UI
Then, when the `experience_started` analytic is trigged on initial render, we can capture and send the new `_sdkMetrics` node in the attributes, for reporting usage.
A few approaches are used to keep this metrics collection from bloating in size at runtime
* only adds entries for things that might potentially trigger qualification - analytics sent …
> Add SdkMetrics to capture timings around experience rendering

- Sources/AppcuesKit/Data/Analytics/ActivityProcessor.swift
- Tests/AppcuesKitTests/Analytics/ActivityProcessorTests.swift
`ActivityProcessor` maintains a `Set` of in-flight request IDs. This set needs to be accessed in a thread-safe manner, so a serial queue is used. However there was one spot where the set was modified outside the safety of the serial queue which could cause a crash if the set was simultaneously being modified from within the queue.
> Fix crash around modifying activity set

- fastlane/build.sh
- release.sh
A couple tweaks from the hot fix release process:
1. the `gh release create` command defaults to `main` which was fine, but not when we're running from a `release/*` branch, so explicitly specify the [target](https://cli.github.com/manual/gh_release_create)
2. the XCFramework build script can fail if the project file is out of date, so run xcodegen first
> Release script enhancements

- Sources/AppcuesKit/Data/Extensions/Array+Chunked.swift
- Sources/AppcuesKit/Data/Models/Experience/ExperienceComponent.swift
- Sources/AppcuesKit/Presentation/UI/Components/AppcuesOptionSelect.swift
- Sources/AppcuesKit/Presentation/UI/Components/NPSView.swift
- Sources/AppcuesKit/Presentation/UI/Components/TintedTextView.swift
Adds support for `"displayFormat": "nps"` in the `optionSelect` model.
Also, a one-line fix to support text wrapping on the survey component label in `TintedTextView`.
corresponding spec change is here https://github.com/appcues/appcues-mobile-experience-spec/pull/102
> Add NPS display format to optionSelect component

- Sources/AppcuesKit/Data/Analytics/AnalyticsTracker.swift
- Sources/AppcuesKit/Data/Models/Experience.swift
- Sources/AppcuesKit/Data/Models/Experiment.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceRenderer.swift
- Tests/AppcuesKitTests/Analytics/ActivityProcessorTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceRendererTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceStateMachineTests.swift
- Tests/AppcuesKitTests/Mocks.swift
- Tests/AppcuesKitTests/Traits/TraitComposerTests.swift
Once we had a real test response to try out, discovered a misunderstanding in the requirements around how the response would look. We need to link the experiment and experience as shown here - matching on the experience ID inside of the experiments array. There is no `experiment_id` in the `experience` response object.
> Fix logic that links experiments and experiences in response

- Sources/AppcuesKit/Data/Models/Experience/ExperienceComponent.swift
- Sources/AppcuesKit/Presentation/UI/Components/MultilineTextView.swift
As per the spec update:
- https://github.com/appcues/appcues-mobile-experience-spec/pull/110
I'm not sure specifically what difference `UITextContentType.URL` makes, but it seems like the right option.
> Add support for the url dataType on textInput

- Examples/DeveloperCocoapodsExample/AppcuesCocoapodsExample.entitlements
- Examples/DeveloperCocoapodsExample/AppcuesCocoapodsExample.xcodeproj/project.pbxproj
- Examples/DeveloperCocoapodsExample/CocoapodsExample/AppDelegate.swift
- Examples/DeveloperCocoapodsExample/CocoapodsExample/DeepLinkNavigator.swift
- Examples/DeveloperCocoapodsExample/CocoapodsExample/SceneDelegate.swift
- Examples/DeveloperCocoapodsExample/Podfile.lock
- Examples/DeveloperCocoapodsExample/README.md
- Sources/AppcuesKit/AppcuesKit.docc/AppcuesKit.md
- Sources/AppcuesKit/AppcuesKit.docc/UniversalLinking.md
- Sources/AppcuesKit/Presentation/Actions/Appcues/AppcuesLinkAction.swift
- Sources/AppcuesKit/Presentation/Extensions/UIApplication+TopViewController.swift
- Tests/AppcuesKitTests/Actions/AppcuesLinkActionTests.swift
This PR adds support for opening universal links in-app. As per the documentation added, an app may implement `UIApplicationDelegate.application(_:continue:restorationHandler:)` which will receive all `https` links that the SDK is asked to open via the `@appcues/link` ("Go To Link") action.
The only slightly tricky bit is that `SFSafariViewController` only supports HTTP and HTTPS URLs and crashes otherwise, and then scheme links crash the `NSUserActivity` link opener, so we have to carefully check to make sure we don't pass the wrong type of link to the wrong handler.
I also opted to include a bit of metadata so an app can detect if the universal link is coming from the Appcues SDK. I don't have a specific user case in mind for this, but it can't hurt.
Resolves #277.
> Support Universal Links for @appcues/link action

- Examples/DeveloperCocoapodsExample/AppcuesCocoapodsExample.entitlements
- Examples/DeveloperCocoapodsExample/project.yml
Developer mode won't work with TestFlight builds:
> As an additional precaution, only apps that you sign with a development profile can use developer mode, and users must opt-in on any device they use.
- https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_associated-domains
> Remove developer mode from universal link entitlements

- Sources/AppcuesKit/Appcues+Config.swift
- Sources/AppcuesKit/Presentation/Actions/Appcues/AppcuesLinkAction.swift
- Tests/AppcuesKitTests/Actions/AppcuesLinkActionTests.swift
This approach would allow a customer to opt-out of the universal link handling logic, if their app was not compatible with this approach. The issue here arose in Ionic apps, and we can update our Capacitor plugin to disable this feature, by default, to avoid common issues.
> Add configuration option to control universal link handling

- Sources/AppcuesKit/Data/Extensions/UUID+Custom.swift
- Sources/AppcuesKit/Data/Models/Experiment.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceRenderer.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/LifecycleEvent.swift
- Tests/AppcuesKitTests/Experiences/ExperienceRendererTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceStateMachine+AnalyticsObserverTests.swift
* capture 2 new properties from the response for experiments
* update the `experience_entered` analytic to output 3 additional properties and rename another
Also added extension on `UUID` for string formatting, as originally mentioned in https://github.com/appcues/appcues-ios-sdk/pull/283#discussion_r1024438630
> Rework experiment analytics to support new requested properties

- Sources/AppcuesKit/Data/Analytics/AnalyticsTracker.swift
- Sources/AppcuesKit/Data/Extensions/UUID+Custom.swift
- Sources/AppcuesKit/Data/Models/Experience.swift
- Sources/AppcuesKit/Data/Models/QualifyResponse.swift
- Sources/AppcuesKit/Data/Networking/DecodingError+Custom.swift
- Sources/AppcuesKit/Data/Networking/UnkeyedCodingContainer+Skip.swift
- Tests/AppcuesKitTests/Analytics/ActivityProcessorTests.swift
- Tests/AppcuesKitTests/Networking/PartialDictionaryDecodeTests.swift
- Tests/AppcuesKitTests/Networking/QualifyResponseDecodeTests.swift
The general concept is very similar to what was done on Android https://github.com/appcues/appcues-android-sdk/pull/278
* `QualifyResponse` now has `[LossyExperience]` instead of `[Experience]`
* There are two possible types - a normal `.decoded(Experience)` and a `.failed(FailedExperience)`
* `FailedExperience` captures minimal info that could hopefully be used to report flow issues for troubleshooting later
* custom deserialization in the `QualifyResponse` does the attempted `Experience` deserialization on each item, error handling and capturing detailed error message, and then fallback handling for failures
an example failure message might look like this for the case of a missing required key
```
key 'CodingKeys(stringValue: "type", intValue: nil)' not found: No value associated with …
```
> Support lossy decoding of Experience objects in qualify response

- Sources/AppcuesKit/Data/Analytics/AnalyticsTracker.swift
- Sources/AppcuesKit/Data/Models/Experience.swift
- Sources/AppcuesKit/Data/Networking/DecodingError+Custom.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine+State.swift
- Sources/AppcuesKit/Presentation/UI/ExperienceData.swift
- Tests/AppcuesKitTests/Analytics/ActivityProcessorTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceStateMachineTests.swift
- Tests/AppcuesKitTests/Networking/QualifyResponseDecodeTests.swift
Use the info from the `FailedExperience` (minimal decode) to construct a fake `Experience` object, with an error message, solely for the purpose of recording a flow issue to diagnose the decoding failure.
Also shows in debugger - in this case, two experiences qualified. The first item failed to decode and logged error. The second item was rendered.
> Log flow issue on experience that failed decoding

- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesBackdropTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesBackgroundContentTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesCarouselTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesPagingDotsTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesSkippableTrait.swift
- Sources/AppcuesKit/Presentation/Traits/DefaultContainerViewController.swift
- Sources/AppcuesKit/Presentation/Traits/ExperiencePackage.swift
- Sources/AppcuesKit/Presentation/Traits/ExperienceTrait.swift
- Sources/AppcuesKit/Presentation/Traits/TraitComposer.swift
- Tests/AppcuesKitTests/Experiences/ExperienceRendererTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceStateMachineTests.swift
- Tests/AppcuesKitTests/Mocks.swift
- Tests/AppcuesKitTests/Traits/TraitComposerTests.swift
This PR adds `undecorate` methods to `ContainerDecoratingTrait` and `BackdropDecoratingTrait` (a breaking change from 1.x) and updates TraitComposer to call these methods at the right time. It also implements the propagation of experience-level and group-level decorating traits to the step-level so that they can be decorated/undecorated as expected.
The remaining changes are to facilitate proper error reporting from the decorate/undecorate sequence. Prior to this PR, all traits were applied immediately in the `TraitComposer.package()` method, so we could handle errors right away. Now, decorations that throw errors are applied as the user navigates through a step group. The best way to handle this is to apply the decorations in the state machine where we can easily log the error events and …
> Update Decorating traits to be removeable when applied at a step level [Traits 2.0]

- Examples/DeveloperCocoapodsExample/AppcuesCocoapodsExample.xcodeproj/project.pbxproj
- Examples/DeveloperCocoapodsExample/CocoapodsExample/AppDelegate.swift
- Examples/DeveloperCocoapodsExample/CocoapodsExample/DeepLinkNavigator.swift
- Examples/DeveloperCocoapodsExample/CocoapodsExample/SceneDelegate.swift
- Examples/DeveloperCocoapodsExample/Podfile.lock
- Examples/DeveloperSPMExample/AppcuesSPMExample.entitlements
- Examples/DeveloperSPMExample/AppcuesSPMExample.xcodeproj/project.pbxproj
- Examples/DeveloperSPMExample/README.md
- Examples/DeveloperSPMExample/SPMExample/AppDelegate.swift
- Examples/DeveloperSPMExample/SPMExample/DeepLinkNavigator.swift
- Examples/DeveloperSPMExample/SPMExample/SceneDelegate.swift
- Examples/DeveloperSPMExample/project.yml
stacking this branch on top of #283 for simpler review
This is addressing the cleanup noted in [this comment](https://github.com/appcues/appcues-ios-sdk/pull/283#discussion_r1024431839)
Previously, only Cocoapods was set up for Universal Links, now they both are. Both are then refactored a bit to consolidate link logic and handle the concept of the `AppcuesNavigationDelegate` - where the Appcues SDK can request navigation with a completion handler.
The implementations of `AppDelegate`, `ScreenDelegate` and `DeepLinkNavigator` are identical now. For the SPM example to work, we'll need the update applied to the [AASA file](https://appcues-mobile-links.netlify.app/.well-known/apple-app-site-association) to add an entry for app ID `KHSQ25769M.com.appcues.sdk-example-spm"`
> Sync up SPM and Cocoapods examples for handling iOS Universal Links and implementing AppcuesNavigationDelegate

- Sources/AppcuesKit/Presentation/Debugger/Panel/DebugUI.swift
Side note, noticed that `NavigationView` is on the way out, in favor of `NavigationStack` and `NavigationSplitView`, but that is iOS 16+ minimum. https://developer.apple.com/documentation/swiftui/migrating-to-new-navigation-types
| after | before |
| ---- | ---- |
| ![Simulator Screen Shot - iPad Pro (12 9-inch) (6th generation) - 2022-12-12 at 10 13 26](https://user-images.githubusercontent.com/19266448/207082907-d6953939-6e3e-43f1-9fbf-486eb0286c24.png)  | ![Simulator Screen Shot - iPad Pro (12 9-inch) (6th generation) - 2022-12-12 at 10 06 54](https://user-images.githubusercontent.com/19266448/207083015-25f61964-a2e1-4921-8238-95f473b23bf1.png) |
> Fix Debugger expanded view layout on iPad

- Sources/AppcuesKit/Data/Models/Experience.swift
- Tests/AppcuesKitTests/Networking/ExperienceDecodeTests.swift
targeting `traits-2.0`
This is part of the 2.0 work where we've made the decision to enforce that a certain trait type, i.e. `@appcues/backdrop`, can only have a single instance at any given level of the experience (typically group or step level definitions).
* Added custom decoding in `TraitCollection` object that detects duplicate trait `type` keys at any given level, and throws a `DecodingError` if encountered.
* Updated to use in `Experience`, `Experience.Step.Group` and `Experience.Step.Child` decoding
* Tests to validate each error case and normal non-error case
If the error is detected, it will result in an Experience error like shown here
> Enforce single instance of each trait type at each level

- Sources/AppcuesKit/Appcues.swift
- Sources/AppcuesKit/Data/Analytics/AnalyticsTracker.swift
- Sources/AppcuesKit/Data/Models/Experience.swift
- Sources/AppcuesKit/Presentation/Actions/Appcues/AppcuesLaunchExperienceAction.swift
- Sources/AppcuesKit/Presentation/DeepLinkHandler.swift
- Sources/AppcuesKit/Presentation/ExperienceLoader.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine+State.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceTrigger.swift
- Sources/AppcuesKit/Presentation/UI/ExperienceData.swift
- Tests/AppcuesKitTests/Actions/AppcuesLaunchExperienceActionTests.swift
- Tests/AppcuesKitTests/AppcuesTests.swift
- Tests/AppcuesKitTests/DeepLinkHandlerTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceLoaderTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceRendererTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceStateMachineTests.swift
- Tests/AppcuesKitTests/MockAppcues.swift
- Tests/AppcuesKitTests/Mocks.swift
- Tests/AppcuesKitTests/Traits/TraitComposerTests.swift
Stacks on other step navigation work in #283 
Analogous to what was done on Android side in https://github.com/appcues/appcues-android-sdk/pull/281
This PR introduces the concept of ExperienceTrigger, which defines the currently six ways an Experience can be triggered:
* builder preview
* qualification
* deep link
* show function call
* launch experience action
* post-flow completion action
This context is now stored on the `ExperienceData` object via passing through at call sites as appropriate. This allows us to detect when an Experience is being launched from a method other than the standard qualification flow, and enable pre-step navigation actions to occur if so. Qualified flows are unchanged - as the location in the app they trigger upon is based entirely on the flow settings …
> Allow navigate actions on first step for non-qualifying experience triggers

- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesBackdropTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesBackgroundContentTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesCarouselTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesModalTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesPagingDotsTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesSkippableTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesStepTransitionAnimationTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesStickyContentTrait.swift
- Sources/AppcuesKit/Presentation/Traits/ExperienceTrait.swift
- Sources/AppcuesKit/Presentation/Traits/TraitComposer.swift
- Sources/AppcuesKit/Presentation/Traits/TraitMetadataDelegate.swift
- Sources/AppcuesKit/Presentation/Traits/TraitRegistry.swift
- Tests/AppcuesKitTests/Traits/TraitComposerTests.swift
- Tests/AppcuesKitTests/Traits/TraitRegistryTests.swift
We've talked about this change a lot, but here's the summary of specifically where I've landed. It's actually pretty simple, which is definitely a win!
1. A `TraitMetadata` object that stores the current and previous metadata values. The previous values are important to allow certain transitions.
2. Every trait has a `TraitMetadataDelegate` that can be used to:
1. set a metadata value for reading by other traits
2. get a metadata value via a handler block. The `type` provided in the block allows a trait to ensure only one instance handles the metadata (rather than, for example, having 2 backdrop traits each trying to animate to the new metadata value). The handler provides a nice wrapper for animating using the metadata values from `@appcues/step-transition-animation`.
3. Publish a new …
> Add TraitMetadataDelegate to manage properties across trait instances and update backdrop trait to animate

- Sources/AppcuesKit/Presentation/Extensions/View+Appcues.swift
- Sources/AppcuesKit/Presentation/UI/AppcuesStyle.swift
- Sources/AppcuesKit/Presentation/UI/Components/AppcuesButton.swift
- Sources/AppcuesKit/Presentation/UI/Components/AppcuesImage.swift
This change reverts and revises what was previously done in #274 , in favor of another approach that will hopefully more closely match the desired outcome of borders being applied in the same way as the CSS border-box style. The issue was around how the border was applied on fixed size elements - and to fix this, the border needs to be applied after the view frame is sized.
When a view does not have any fixed size, just sizing to the intrinsic content size of a label or image, for instance, this inset is _not_ used, and the border just applies on top of the content to increase the overall intrinsic size of the view.
The approach here introduces a new concept of `borderInset`, which gets applied on fixed size height or width elements in a way that reserves some space for a border to be …
> Adjust how border is applied to match CSS border-box style

- Sources/AppcuesKit/Presentation/UI/Components/AppcuesOptionSelect.swift
- Sources/AppcuesKit/Presentation/UI/Components/AppcuesTextInput.swift
- Sources/AppcuesKit/Presentation/UI/Components/EqualWidthStack.swift
Updating the option select **(edit: and text)** component layout to:
1. Always take the full width available (the `HStack` causes this)
2. Visually apply the `optionSelect.style.horizontalAlignment` to the options (L22, but it didn't change)
3. Apply the `optionSelect.label.style.horizontalAlignment` to the question label (previous it was ignored, will default to leading if no value is specified)
4. Apply the `optionSelect.errorLabel.style.horizontalAlignment` to the error label (previous it was ignored, will default to leading if no value is specified)
Consequently, the question label, options, and error can all be horizontally aligned independently of each other.
|Fixed|Broken|
|-|-|
|![Simulator Screen Shot - iPhone 14 Pro - 2023-01-03 at 13 03 …
> Update form components to handle label horizontalAlignment

- Sources/AppcuesKit/Presentation/UI/Components/AppcuesOptionSelect.swift
- Sources/AppcuesKit/Presentation/UI/Components/AppcuesTextInput.swift
Noticed I got this wrong when doing the snapshot test.
The default value (8) means we’d get additional spacing which could in some cases cause text to wrap prematurely when we really just want to use the `Spacer` for alignment purposes.
> Update survey component horizontal spacing

- Tests/AppcuesKitTests/Analytics/AnalyticsBroadcasterTests.swift
- Tests/AppcuesKitTests/Analytics/AnalyticsTrackerTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceRendererTests.swift
- Tests/AppcuesKitTests/MockAppcues.swift
- Tests/AppcuesKitTests/Mocks.swift
Should patch up the build issue reported here https://swiftpackageindex.com/appcues/appcues-ios-sdk/builds, and restore our badge display.
> Fix swift package compilation issue with tests reference iOS 13+ types

- Sources/AppcuesKit/Data/Analytics/AutoPropertyDecorator.swift
- Sources/AppcuesKit/Data/Extensions/UIViewController+Tracking.swift
- Sources/AppcuesKit/Presentation/Debugger/FloatingView/DebugViewController.swift
- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/Capture.swift
- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/UIView+Capture.swift
- Sources/AppcuesKit/Presentation/Debugger/UIDebugger.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ElementSelector.swift
This is the next step of the screen capture work - generating a capture model - the eventual JSON structure that we'll send to the API. A lot of this inspired/adapted from what @mmaatttt did in initial POC work in https://github.com/appcues/appcues-ios-sdk/commit/fa456edbab24c83fd0398931f342f346605ea7df.
The structure here is following on to initial model design work scoped out in [this doc], and currently being worked by the backend team here https://github.com/appcues/customer-api/pull/1041.
There is no UI or confirmation dialog here - that will follow on next. This allows you to open the snapshot button via deep link from previous PR, and then generate this model from the current UIWindow and print to the console (temporarily).
Example output and some comments for discussion are …
> Add initial screen capture model and populate from current UIWindow

- Examples/DeveloperSPMExample/AppcuesSPMExample.xcodeproj/project.pbxproj
- Examples/DeveloperSPMExample/SPMExample/Base.lproj/Main.storyboard
- Examples/DeveloperSPMExample/SPMExample/HomeTabBarController.swift
stacks on #316 
This adds the accessibility info needed for basic selectors on various buttons in our example app - all the main tabs and other buttons and text fields.
Had to add a `HomeTabBarController` implementation with a workaround for setting the tab values, due to the lack of automatic support in UITabBarController.
> Update SPM example with accessibility identifiers

- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine.swift
- Sources/AppcuesKit/Presentation/Traits/ExperiencePackage.swift
- Sources/AppcuesKit/Presentation/Traits/TraitComposer.swift
- Tests/AppcuesKitTests/Traits/TraitComposerTests.swift
This is an update to support the use case of: pre-step navigation, then show a step with a targeted-element that depends on the navigation to the new screen being completed.
Previously, the call to the `TraitComposer.package` function would result in the backdrop decorating traits applying their initial decorations - which could result in target-element lookups occurring. This was happening prior to the execution of the navigation actions, before the presentation of the new container.
Now, the application of initial step decoration is delayed until later in the process, after navigation actions have had a chance to execute - in hte `executePresentContainer` function of `ExperienceStateMachine.SideEffect`
note: this is targeting `traits-2.0` as it primarily relates to target-element …
> Apply traits after any pre-step container navigation executes

- Sources/AppcuesKit/Presentation/Debugger/FloatingView/DebugView.swift
- Sources/AppcuesKit/Presentation/Debugger/FloatingView/DebugViewController.swift
- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/Capture.swift
- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/SendCaptureUI.swift
- Sources/AppcuesKit/Presentation/Debugger/UIDebugger.swift
stacks on #313 
The UI side of things for the capture flow shown in the video below. Did this stuff in SwiftUI just because why not. It doesn't necessarily have to be though. This hooks in to the DebugViewController to present the modal, and then get the updated screen name and pass along for upcoming API integration work (TBD).
https://user-images.githubusercontent.com/19266448/212973639-9d826f29-cf35-4fb7-b82c-70f04cd83e68.mov
> Add confirmation dialog and toast for screen capture flow

- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesTargetRectangleTrait.swift
The target rectangle trait was doing an extra metadata publish on step change from within the frame observer.
Publishing twice on a step change breaks the `@appcues/backdrop-keyhole` animation because the first publish has the correct values to animate but that animation gets replaced by the second publish which has the same values.
Calling `layoutIfNeeded()` *before* adding the observer takes care of the double. Then there's an edge case for the first step in a group where the backdrop view still has zero bounds because it's not in the view hierarchy yet, so checking for the `window` being set means we can skip publishing a value the first time and get a proper animation triggered by the frame observer.
The `@appcues/target-element` trait will likely require similar changes, but I'll …
> Fix double publishing of the target rectangle frame

- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/Capture.swift
- Sources/AppcuesKit/Presentation/Debugger/UIDebugger.swift
This updates the structure to match recent [discussions](https://appcues.slack.com/archives/C02EX9N4067/p1674141246499829) with Humber around API contract. Specifically, moving some fields inside of an unstructured `metadata` property they will store, for future flexibility.
> Update layout capture structure

- Examples/DeveloperCocoapodsExample/AppcuesCocoapodsExample.xcodeproj/project.pbxproj
- Examples/DeveloperCocoapodsExample/CocoapodsExample/Base.lproj/Main.storyboard
- Examples/DeveloperCocoapodsExample/CocoapodsExample/HomeTabBarController.swift
- Examples/DeveloperCocoapodsExample/Podfile.lock
This matches the identifiers that were previously updated in the SPM example in #317, so we can test target element behaviors with this app.
events tab
* tabEvents
* btnEvent1
* btnEvent2
profile tab
* tabProfile
* txtGivenName
* txtFamilyName
* btnSaveProfile
group tab
* tabGroup
* txtGroup
* btnSaveGroup
> Add accessibility identifiers to Cocoapods example app

- Sources/AppcuesKit/Presentation/Traits/Appcues/DialogContainerView.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/DialogContainerViewController.swift
targeting `main` for a potential 1.x release
Support `style.verticalAlignment` for top | center | bottom
| top | center | bottom |
| --- | --- | --- |
| ![Screenshot 2023-01-19 at 3 40 37 PM](https://user-images.githubusercontent.com/19266448/213556900-96d18057-e286-4b75-87dc-2632cc44088c.png) | ![Screenshot 2023-01-19 at 3 41 06 PM](https://user-images.githubusercontent.com/19266448/213556953-5fd0158e-9db5-46b6-9bf9-0a6af837c5f6.png)  | ![Screenshot 2023-01-19 at 3 40 52 PM](https://user-images.githubusercontent.com/19266448/213556970-94f46fe1-13d1-4168-8ff3-13e6eb3d6ee0.png)
|
> Add support for verticalAlignment styling on dialog modal

- Sources/AppcuesKit/Presentation/Extensions/UIBezierPath+Tooltip.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/TooltipWrapperView.swift
Supports 3 scenarios:
1. Regular, centred pointer
2. Right-angle pointer with a rounded corner
3. Right-angle pointer replacing a rounded corner
The `Triangle.init` is super long and complex, but it's really just the same logic 4x (one for each edge) with different values. Anything to make it more concise would incur a huge readability hit.
https://user-images.githubusercontent.com/845681/215852987-59a69af0-3100-4363-bf07-568fb0d6450c.mp4
> Add dynamically adjusting tooltip pointer shapes

- Sources/AppcuesKit/Presentation/Debugger/FloatingView/DebugViewController.swift
- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/DebugModalViewController.swift
- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/SendCaptureUI.swift
- Sources/AppcuesKit/Presentation/UI/Components/MultilineTextView.swift
Three commits here to address the pieces
1. Extract out a protocol for the MultiLineTextView component to use for its model properties so that it could be shared with this use case, and we could get the "done" toolbar that is not available in SwiftUI in iOS 13
2. Update the SendCaptureUI dialog contents to use this text view implementation instead of the SwiftUI version
3. (the largest part) - rework the hosting ViewController structure to support loading our dialog contents, in SwiftUI, inside of a UIViewController that properly handles the keyboard avoidance and scrolling focused text view into visible region
The implementation of DebugModalViewController adapts ideas from the ExperienceWrapperViewController and ExperienceStepViewController, but condenses them down into a single …
> Fix keyboard avoidance with the send capture dialog

- Sources/AppcuesKit/Presentation/Debugger/FloatingView/FloatingView.swift
This is to address an issue Ben saw in https://www.loom.com/share/2cbb97aee89144d599088a617021223e
where the FAB can end up square like:
Open to alternative ideas to best handle, but here is what is causing it:
* The FAB is hidden while the confirmation dialog is shown
* This calls FloatingView.animateVisibility - which hides the view by animating alpha to zero, but also does a CGAffineTransform shrink of the view down to a tiny size
* When the app is backgrounded, `layoutSubviews` is called for some reason on FloatingView. This causes a recalculation of the cornerRadius to occur. At this point `frame.width` is something very tiny so the cornerRadius is set to effectively zero - resulting in the square.
This change will skip that cornerRadius calculation if the view is not visible (alpha …
> Only apply cornerRadius to FAB when visible

- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesStepTransitionAnimationTrait.swift
Note that `AppcuesStepTransitionAnimationTrait.duration` on L21 is a `TimeInterval` which is defined as seconds, so the unit should be clear.
> Update animation duration to parse from milliseconds

- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesTargetElementTrait.swift
Still pondering best approach here, but this is an idea that uses a concept of weighted match - where some selector property matches are considered more valuable than others, and the largest weighted match value is considered the selected element if found. We could evolve what set of properties are used and how they are weighted over time.
This allows for multiple properties to be combined for a more distinct selector. If there is still no single highest value match, it fails element selection as before.
> Use a weighted matching approach for element selector

- Sources/AppcuesKit/Data/Models/Experience/ExperienceComponent.swift
- Sources/AppcuesKit/Presentation/UI/Components/AppcuesText.swift
- Sources/AppcuesKit/Presentation/UI/Components/TintedTextView.swift
The updated text model requires at least one of `spans` or `text`. If both are present, `spans` is preferred. If neither are present, it's a decoding error. The custom decoder enforces this efficiently.
`text` will continue to be provided by the mobile builder for backwards compatibility with previous SDK versions, but making `text` optional here, allows us to eventually remove it in favour of only `spans` in the future if we're able to remove support for SDK versions that don't include this change.
```json
{
"type": "button",
"id": "b947f397-80bd-4dc2-8264-850333609558",
"content": {
"type": "text",
"id": "00591d74-20b6-4377-af5f-c67571d67e27",
"text": "Next",
"style": {
"fontSize": 17,
"foregroundColor": { "light": "#ffffff" }
},
"spans": [
{
"text": "N",
"style": {
"fontName": …
```
> Add support for multiple text styles in a single primitive

- Sources/AppcuesKit/Data/Models/SdkMetrics.swift
- Tests/AppcuesKitTests/Analytics/SdkMetricsTests.swift
The test fails reliably before the fix and never after the fix with hundreds of runs.
Note that `trackRender` is the only case of `syncQueue.sync`, the rest can be `async`.
> Fix crash from lack of thread safety in SdkMetrics

- Sources/AppcuesKit/Presentation/UI/ExperienceStepViewController.swift
The previous approach was to inset the safe area of ExperienceStepViewController by the size of the sticky content and then set the sticky content outside the safe area. 
This was causing extra layout passes because SwiftUI knew the content was in the safe area and basically didn't appreciate that fact. It was slow in some cases and actually froze the app in one particularly extreme example that Ben found.
We also had an issue where the sticky content was taller than than available container height (especially notable in half sheets) and so the safe areas exceeded the container height and left no space for the content. This is user error in the experience design to a certain extent, but the way it was displayed on iOS looked even more broken. Now the sticky content will still entirely …
> Update sticky content to work using safe area

- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesCarouselTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/TooltipWrapperView.swift
- Sources/AppcuesKit/Presentation/UI/ExperienceStepViewController.swift
Two little fixes in two commits.
First, we want to cap the pointer width to not be wider than the tooltip. Not a likely case, but it looked really bad when it happened.
Second, for leading/trailing tooltips, the content was going into the safe area in the pointer. This is because of a workaround for landscape mode fullscreen carousel modals. I looked into fixing the carousel case a different way, but came up blank, so I've changed the workaround to only be applied by the carousel trait, rather than affecting everything and now tooltips display properly too.
|Good|Bad|
|-|-|
|![good pointer](https://user-images.githubusercontent.com/845681/218848286-9aa701da-e234-4b2f-aeed-acd95fe6e5d9.png)|![bad pointer](https://user-images.githubusercontent.com/845681/218848323-94c40610-53d1-4c15-a658-a8b …
> Tooltip UI enhancements

- Sources/AppcuesKit/Data/Networking/DecodingError+Custom.swift
- Sources/AppcuesKit/Presentation/Debugger/Panel/DebugViewModel.swift
- Tests/AppcuesKitTests/Networking/QualifyResponseDecodeTests.swift
Random little thing, but I was annoyed trying to figure out where an error in my JSON was, so I improved the messages. They're shorter and clearer now:
```
// Old
key 'CodingKeys(stringValue: "type", intValue: nil)' not found: No value associated with key CodingKeys(stringValue: "type", intValue: nil) ("type"). codingPath: [_JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "steps", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)]
// New
Expected key 'type' not found at codingPath: 0.steps.0
// Old
value 'String' not found: Expected String value but found null instead. codingPath: [_JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "steps", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "type", …
```
> Update experience decoding error test

- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceRenderer.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine.swift
- Tests/AppcuesKitTests/Experiences/ExperienceRendererTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceStateMachineTests.swift
Requested change for parity with web, and to make our Studio analytics dashboards more comprehendible for customers.
> Do not mark experience completed if dismissed on the final step

- fastlane/Fastfile
- fastlane/README.md
When our distribution certificate expires, this is the option needed to `nuke` (remove from dev portal and S3) and then regenerate, using existing `prep_match`.
```
fastlane nuke_match
```
Should really only be run once, as it will wipe all the profiles out, including the Cocoapods example here and all other iOS example apps we have in our App Store connect profile. Then, visit each product and run 
```
fastlane prep_match
```
To regenerate the profile for that product.
The option for `fastlane reset_match` is just a convenience to do a nuke + prep.
> Add fastlane option to nuke and regenerate certs and profiles with match

- Sources/AppcuesKit/Appcues.swift
- Sources/AppcuesKit/Data/Analytics/AutoPropertyDecorator.swift
- Sources/AppcuesKit/Data/Extensions/UIDevice+Custom.swift
- Sources/AppcuesKit/Data/Models/Activity.swift
- Tests/AppcuesKitTests/AppcuesTests.swift
targets `main` for a potential 1.3.1 release
Matching web SDK behavior by adding an `anon:` prefix on any anonymous user ID generated and used in the `anonymous()` function call. Backend services can use this convention to reliably differentiate anonymous user traffic.
Also updated the default value `identifierForVendor` to use `.appcuesFormatted` (lowercase). This value is also the `_localId` auto prop. Also, a couple of other UUID spots: `_sessionId` auto prop, and `request_id` top level value, updated to lowercase to match other usages in Appcues backend and other clients.
> Add anonymous user ID prefix

- Sources/AppcuesKit/Appcues.swift
- Sources/AppcuesKit/AppcuesKit.docc/Debugging.md
- Sources/AppcuesKit/AppcuesKit.docc/Extensions/Appcues.md
- Sources/AppcuesKit/AppcuesKit.docc/Identifying.md
This is a `traits-2.0` branch change (breaking) - we'll no longer support properties passed in on anonymous() user calls. This is to match the web SDK and comply with data security expectations.
> Remove the properties parameter from anonymous function

- Sources/AppcuesKit/Presentation/Traits/Appcues/TooltipWrapperView.swift
Working on the JS implementation caught that I missed a case in #331
|Fixed|Broken|
|-|-|
|![Simulator Screen Shot - iPhone 14 Pro - 2023-02-24 at 14 54 32](https://user-images.githubusercontent.com/845681/221278725-a6abab3f-f0df-4b10-b28d-579fb46099d6.png)|![Simulator Screen Shot - iPhone 14 Pro - 2023-02-24 at 14 54 21](https://user-images.githubusercontent.com/845681/221278734-6409f1f2-b4e0-4c4e-b68b-340b6638e5cc.png)|
> Update tooltip layout to respect bottom safe areas and always render fully on screen

- Sources/AppcuesKit/Data/Networking/Endpoint.swift
- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/Capture.swift
- Sources/AppcuesKit/Presentation/Debugger/UIDebugger.swift
Also fix a double `?` on query string of pre-signed image upload request.
> Add safe area insets to screen capture metadata

- Sources/AppcuesKit/Presentation/Traits/Appcues/TooltipWrapperView.swift
- Sources/AppcuesKit/Presentation/Traits/DefaultContainerViewController.swift
Enforces a min height on the tooltip content (meaning the tooltip may ignore the `contentDistanceToTarget` value and even be positioned over the target rectangle (if it's really large).
The second change I want to make is switching to left/right tooltips when there's space available (primarily considering landscape mode scenarios here). To do that I want to combine `verticalPosition()` and `horizontalPosition()` into a single function to add support for the `TODO: Should this consider a switch to horizontal if there's not enough vertical space on either side?`, but wanted to get this changed PRed first for the sake of clarity.
> Update tooltip layout to have a minimum content height

- Sources/AppcuesKit/Presentation/Traits/Appcues/TooltipWrapperView.swift
I'd recommend not looking at the diff for this one and just looking at the new `tooltipPosition(for:)` function. I've combined the logic for vertical and horizontal and addressed the `// TODO: Should this consider a switch to horizontal if there's not enough vertical space on either side?`.
The new code should also be much easier to follow because the decision about where the tooltip is displayed (L165-L180) is better separated from actually calculating the position (L182-L249). Now it's a linear `if/else if/else` to decide on the position instead of the nested mess from before. Then it's a simpler switch to actually calculate the frame for a given position. Another benefit is the frame calculation for a given orientation is only done in one place vs the several before which means fewer …
> Update tooltip positioning to change orientation when space is available

- Sources/AppcuesKit/Presentation/UI/ExperienceStepViewController.swift
Having to manage the scroll insets separately now is a bit annoying, but I haven't found a nicer solution.
Example with 10px padding on all sides, no margins on anything, and the image/button sticky top/bottom respectively:
> Apply step padding to sticky content

- Sources/AppcuesKit/Presentation/Traits/Appcues/TooltipWrapperView.swift
- Tests/AppcuesKitTests/Experiences/TooltipWrapperViewFrameTests.swift
And the tests caught a layout issue for the bottom sheet cases (when there's no target rectangle available).
> Add tests for tooltip frame calculations

- Sources/AppcuesKit/Presentation/Debugger/FloatingView/DebugView.swift
- Sources/AppcuesKit/Presentation/Debugger/FloatingView/DebugViewController.swift
- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/CaptureToastView.swift
- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/SendCaptureUI.swift
- Sources/AppcuesKit/Presentation/Debugger/UIDebugger.swift
This is a second swing at what was done in #352 , using a simplified approach that implements the toasts in a UIView, rather than having to [deal with all the complexities](https://github.com/appcues/appcues-ios-sdk/pull/352#discussion_r1126649047) of hosting a SwiftUI toast view inside of a UIKit container.
The end result should look and behave identically to the previous PR.
* Toast shows 3 sec on success, 6 sec on failure
* Tapping retry button triggers another save attempt with the same capture and token (useful in rare client network glitch case)
* Tapping anywhere else outside of the toast, or any part of the toast other than the button will initiate a dismiss
Success
https://user-images.githubusercontent.com/19266448/223795054-e1f82f63-6455-4332-a1b5-ad4e3b247351.mov
Failure …
> Add success and failure toast implementations for screen capture using simplified UIView

- Sources/AppcuesKit/AppcuesKit.docc/Identifying.md
There will be another doc the security team maintains about the overall process, getting and SDK key, and enabling your account. This is meant to be an implementation detail reference that the other doc can point to for each type of SDK. We also plan to link back to the main doc, when it is available.
> Update documentation to note sender validation usage

- .circleci/config.yml
Trying out a deploy from `main` here https://app.circleci.com/pipelines/github/appcues/appcues-ios-sdk/1707/workflows/cbd14ec4-dfc8-4cf0-ad3f-a9a1a0afda4d/jobs/1558
> Update Circle CI to use Xcode 14.2

- Sources/AppcuesKit/Presentation/UI/Components/AppcuesText.swift
- Sources/AppcuesKit/Presentation/UI/Components/TintedTextView.swift
For reference, `TintedTextView` is used exclusively by `AppcuesOptionSelect` and `AppcuesTextInput` to show the label. We skip applying the rich text color which allows the errorTintColor to be applied to the whole rich text object.
|Error Tint|Regular Rich Text|
|-|-|
|![Simulator Screen Shot - iPhone 14 Pro - 2023-03-28 at 11 25 13](https://user-images.githubusercontent.com/845681/228288014-81670d33-8c5c-4129-a283-d9a991a47631.png)|![Simulator Screen Shot - iPhone 14 Pro - 2023-03-28 at 11 25 11](https://user-images.githubusercontent.com/845681/228288004-5557d225-520e-49e5-9b9a-53fd8d442118.png)|
> Ensure an error color overrides rich text coloring

- fastlane/Fastfile
Ignoring these directories will improve the usefulness of the codecov reports on PRs. It'll also remove the annoying inline warnings about missing coverage for things that won't ever be tested with unit tests in this repository.
> Update code coverage to exclude presentation files

- Sources/AppcuesKit/Presentation/Extensions/UIApplication+TopViewController.swift
A bit related to #375 and using `isAppcuesWindow`... It's always been the case that a modal can appear on top of the debugger (usually when you have Charles constantly returning a qualified experience) which is because the debugger window claims the `activeKeyWindow` mantle. The same thing can happen for tooltips, which is even stranger, so I figured we should clean this up.
I still want to use `activeKeyWindow` to theoretically support multi-window iPad apps properly, so I'm keeping that but checking if it's `isAppcuesWindow` and then falling back to a simpler window detection.
This method is used by the modal trait, the tooltip trait, and a handful of other places that I've verified should **prefer** (or be **indifferent** to) this new behaviour:
- State machine looking for …
> Ensure experiences aren’t presented over the debugger

- Sources/AppcuesKit/Presentation/Traits/Appcues/TooltipWrapperView.swift
In #365 I did [🐛 Fix tooltip content clipping during initial layout](https://github.com/appcues/appcues-ios-sdk/pull/365/commits/dd0c1f9560080c8612e6c2d178570bbf87eb70b7), but that didn't work properly with border widths because the frame width/height for the inner mask was including the border width. Changed that and also made sure the initial width is 0 instead of 1.
|Fixed|Broken|
|-|-|
|![Simulator Screen Shot - iPhone 14 Pro - 2023-04-06 at 11 28 46](https://user-images.githubusercontent.com/845681/230427178-4f67ddb4-34ff-45c4-8cd3-988180ecc561.png)|![Simulator Screen Shot - iPhone 14 Pro - 2023-04-06 at 11 28 14](https://user-images.githubusercontent.com/845681/230427220-67dd0e4e-9a79-45bb-a498-c6128df14326.png)|
> Fix tooltip corner radius when there’s a border

- Tests/AppcuesKitTests/PublicAPITests.swift
I mentioned wanting to do this a while back, but now is a good time as we prep for 2.0. This tests everything that's currently `public` in the SDK, with the idea that changing those things would cause the test case to fail to compile and act as a reminder that we require a major version bump.
When I update this for 2.0, it'll be a good way to create a migration guide when for example, this was removed:
```swift
_ = Font.Design.allCases
_ = Font.Design.default.description
_ = Font.Weight.allCases
_ = Font.Weight.regular.description
```
This test class obviously won't notify us about new public API additions, so we'll need to remember to add them.
In the process of creating this I noticed that we have a public `TraitError` with the intent that a custom trait could throw an instance, but …
> Add test harness that implements the breadth of the public interface

- Sources/AppcuesKit/Presentation/Actions/ActionRegistry.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine.swift
- Sources/AppcuesKit/Presentation/Public/ExperiencePluginConfiguration.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesBackdropKeyholeTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesBackdropTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesBackgroundContentTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesCarouselTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesModalTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesPagingDotsTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesSkippableTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesStepTransitionAnimationTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesTargetElementTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesTargetRectangleTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesTooltipTrait.swift
- Sources/AppcuesKit/Presentation/Traits/ExperienceTrait.swift
- Sources/AppcuesKit/Presentation/Traits/TraitComposer.swift
- Sources/AppcuesKit/Presentation/Traits/TraitRegistry.swift
- Sources/AppcuesKit/Presentation/UI/ExperienceStepViewModel.swift
- Tests/AppcuesKitTests/Actions/ActionRegistryTests.swift
- Tests/AppcuesKitTests/Actions/StepInteractionActionTests.swift
- Tests/AppcuesKitTests/ExperiencePluginConfiguration+Testable.swift
- Tests/AppcuesKitTests/PublicAPITests.swift
- Tests/AppcuesKitTests/Traits/TraitComposerTests.swift
- Tests/AppcuesKitTests/Traits/TraitRegistryTests.swift
Way back in https://github.com/appcues/appcues-ios-sdk/pull/231 we added `ExperienceTraitLevel` which gets passed in the `ExperienceTrait.init`. This is fine as is, but it’s really not something that gets used much (it was designed only for one specific trait), so I was thinking we could move it into `ExperiencePluginConfig` as a property. This in theory has a few benefits, none of which are huge, but add up to a nice improvement:
1. `ExperienceAction` inits could now use this (not that we have a real good use case for it, but it would allow a trait to know if it’s being used at the group level)
2. The trait init is simpler and we have a pattern to include other new things in the plugin config object instead of the trait init which creates more flexibility for us to add things (including …
> Move ExperienceTraitLevel to ExperiencePluginConfiguration

- .circleci/config.yml
- fastlane/Fastfile
The `Uploading test results` (to CircleCI) step was always failing ([example](https://app.circleci.com/pipelines/github/appcues/appcues-ios-sdk/1768/workflows/bd66840e-877b-436a-ab61-0b92d98fc876/jobs/1620/parallel-runs/0/steps/0-110)) because it was trying to upload the cobertura file. Specifying the file that we do what fixes that.
Separately, the Codecov upload fails sometimes with various errors (but the Circle step always passes regardless) so I bumped the codecov orb version and updated a couple slather config items to see if that makes it more reliable. I don't have great sense of why it's flaky, and it's not worth a ton of time to investigate.
> Update CI test config

- Gemfile.lock
I think I goofed on this in #389 just merged, when the platform `x86_64-darwin-22` was added. Running `bundle install` actually generates a few other updates in the file and I think we need to keep this updated for build cache to work correctly.
> Add missing entries in Gemfile.lock

- Sources/AppcuesKit/Presentation/Actions/ActionRegistry.swift
- Sources/AppcuesKit/Presentation/Public/Plugins/AppcuesExperiencePluginConfiguration.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesTargetBehaviorTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesTargetInteractionTrait.swift
- Sources/AppcuesKit/Presentation/Traits/TraitRegistry.swift
- Tests/AppcuesKitTests/ExperiencePluginConfiguration+Testable.swift
This adds an implementation of `@appcues/target-interaction` (naming tbd, [spec PR](https://github.com/appcues/appcues-mobile-experience-spec/pull/175)). This trait can be used to create a transparent UIView that lays over the target rectangle, from metadata, and captures taps and long presses. The trait can supply actions to take on those interactions, using standard experience action format. If no actions are provided, the trait simply captures those interactions and prevents them from flowing through to the backdrop - meaning it would not dismiss the flow, for example, if the skippable trait was otherwise dismissing on other backdrop taps.
One notable update is that `AppcuesExperiencePluginConfiguration` now includes the `Appcues` instance. This was made available here so that traits …
> Add target interaction trait to control interactions with target rectangle

- Sources/AppcuesKit/AppcuesKit.docc/Identifying.md
Requested naming update to align with the feature name throughout Appcues documentation.
> Use identity verification instead of sender validation for feature name in docs

- .circleci/config.yml
This is the other half of https://github.com/appcues/appcues-mobile-experience-spec/pull/185 based on https://circleci.com/blog/pipeline-orchestration-circleback/
There's 3 new jobs here:
1. `trigger-spec-test-pipeline` where we want to run the unit tests alongside the snapshot tests, so we trigger the `appcues-mobile-experience-spec` pipeline (trying first for a branch name matching the one triggering and then falling back to `main`) with the name of the branch we want to test against.
2. `wait-for-spec-test-pipeline` an approval job that suspends this pipeline until an approval action is triggered (in this case by the `appcues-mobile-experience-spec` pipeline.
3. `check-status-of-spec-test-pipeline` where we use the saved ID of the triggered job to get its status, and if successful get …
> Add pipeline orchestration to run snapshot tests in spec repo

- Sources/AppcuesKit/Data/Extensions/UUID+Custom.swift
- Sources/AppcuesKit/Presentation/UI/ExperienceData.swift
- Tests/AppcuesKitTests/Analytics/AnalyticsBroadcasterTests.swift
Found in https://appcues.slack.com/archives/C03JYPH1NJZ/p1684250936524709
I tried to survey the rest of the codebase to make sure we don't have this issue anywhere else, but it's a bit tricky to be sure. We've got it correct already in places like https://github.com/appcues/appcues-ios-sdk/blob/fab91923f6ad9624164c7d9abdd5bf6d65ac620c/Sources/AppcuesKit/Data/Models/Activity.swift#L58
> Fix format of survey form response field ID

- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/UIKitElementTargeting.swift
- Tests/AppcuesKitTests/Traits/AppcuesStepTransitionAnimationTraitTests.swift
- Tests/AppcuesKitTests/Traits/AppcuesTargetElementTraitTests.swift
- Tests/AppcuesKitTests/Traits/AppcuesTargetRectangleTraitTests.swift
Adding some unit tests for traits that for functionality that can be easily tested without snapshot tests. `UIKitElementTargeting` is indirectly tested via the trait. It might not be a bad idea to add more tests for specific edge cases in `UIKitElementTargeting` later on, but this covers the basics.
> Trait unit tests

- Sources/AppcuesKit/Data/Models/Experience.swift
- Sources/AppcuesKit/Presentation/UI/Components/EnvironmentValues+ImageCache.swift
A couple little changes that:
1. Allow for trait snapshot tests of sticky content. The trait snapshot system uses the `Experience.init()` which wasn't handling sticky content (not a bug since that init never gets used that way outside of tests). Sticky content isn't specifically a trait (anymore), but it can be tested nicely that way with injecting the list of primitives.
2. Making `ImageCacheKey.defaultValue` mutable allows us to set the default value in tests to a subclass of `SessionImageCache` that dynamically maps requests to the asset catalog instead of the [current verbose way](https://github.com/appcues/appcues-mobile-experience-spec/blob/51f2958d061ee0caed827c144a7276630f721a0f/verification-suites/ios/SnapshotTests/XCTestCase%2BComponentSnapshot.swift#L160-L176) we prime the …
> Update inits for testability

- Sources/AppcuesKit/Presentation/DeepLinkHandler.swift
- Sources/AppcuesKit/Presentation/Extensions/UIApplication+TopViewController.swift
- Tests/AppcuesKitTests/Actions/AppcuesLinkActionTests.swift
- Tests/AppcuesKitTests/DeepLinkHandlerTests.swift
I'm in the process of creating UI tests for launching the debugger (and screen capture) using deep links and realized it's not working properly for one of the scenarios. If the client app isn't in the foreground, there's a mismatch checking the state and so the debugger launching fails.
There's also the case where the app is foregrounded which isn't really possible on a device launching from a QR code in the camera app, but is often the case when launching the deep link on a simulator, which I think is why we haven't noticed it not working. Additionally, the experience preview deep link always works because the way it presents the experience is different than the logic used in the debugger.
UI tests to follow in the spec repo.
> Fix deep link launching debugger when app is backgrounded

- Sources/AppcuesKit/Data/Extensions/UIViewController+Tracking.swift
- Sources/AppcuesKit/Data/Networking/Endpoint.swift
- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/AppcuesTargetView.swift
- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/ScreenshotUpload.swift
- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/UIDebugger+Capture.swift
- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/UIKitElementTargeting.swift
- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/UIView+Capture.swift
- Sources/AppcuesKit/Presentation/Debugger/UIDebugger.swift
- Sources/AppcuesKit/Presentation/Public/ElementTargeting/View+AppcuesView.swift
The modifier adds a background `AppcuesTargetView` `UIView` which has the same frame as a the tagged view, allowing it to be targeted.
Also updating the default Name of captured screens to be nicer for SwiftUI views and removed the (now) redundant timestamp.
> Add View modifier to support SwiftUI element targeting

- Sources/AppcuesKit/Presentation/Debugger/FloatingView/DebugViewController.swift
- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/CaptureToastView.swift
- Sources/AppcuesKit/Presentation/Debugger/UIDebugger.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesTargetElementTrait.swift
- Tests/AppcuesKitTests/Traits/AppcuesTargetElementTraitTests.swift
The debugger now has a dependency on the `ExperienceRenderer` to be able to dismiss an experience if needed before performing a screen capture:
Also took care of sc-53273 and rename the target-element trait, as well as added a toast message in place of a silent failure if the screen capture fails.
> Ensure experiences are dismissed before screen capture

- Sources/AppcuesKit/Vendor/UIImage+BlurHash.swift
I was playing around with a couple [Swift compiler flags](https://www.jessesquires.com/blog/2017/09/18/measuring-compile-times-xcode9/)
```
-Xfrontend -warn-long-function-bodies=<limit-ms>
-Xfrontend -warn-long-expression-type-checking=<limit-ms>
```
This change reduces building the whole AppcuesKit framework from an average of 7.83s to 5.76s, a ~26% improvement. (Obviously exact values vary from machine to machine)
> Update BlurHash init to optimize compile time

- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/UIKitElementTargeting.swift
- Sources/AppcuesKit/Presentation/Public/ElementTargeting/AppcuesViewElement.swift
- Tests/AppcuesKitTests/PublicAPITests.swift
- Tests/AppcuesKitTests/Traits/AppcuesTargetElementTraitTests.swift
The `displayName` property in the init must be optional so that it's not a breaking change, and then swift convention dictates that optional init parameters are last in the list.
I reworked `asViewElement(in:)` a bit to avoid recomputing the selector or type determination.
> Add displayName to AppcuesViewElement

- Sources/AppcuesKit/Presentation/Extensions/Inits/NSDirectionalEdgeInsets+Style.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesModalTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesPagingDotsTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesSkippableTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesTooltipTrait.swift
Realized I was going to use the `NSDirectionalEdgeInsets` snippets again for embeds, so adding an extension to init from `ExperienceComponent.Style`.
> Add custom NSDirectionalEdgeInsets initializers for convenience

- Sources/AppcuesKit/Appcues+Config.swift
- Sources/AppcuesKit/Presentation/Extensions/Inits/Font+Double.swift
- Sources/AppcuesKit/Presentation/Traits/TraitComposer.swift
- Sources/AppcuesKit/Presentation/UI/Components/AppcuesText.swift
- Sources/AppcuesKit/Presentation/UI/Components/TintedTextView.swift
- Sources/AppcuesKit/Presentation/UI/ExperienceStepViewModel.swift
- Tests/AppcuesKitTests/PublicAPITests.swift
aka Dynamic Type accessibility
This approach would provide a config option to `.enableTextScaling(enabled)`. This option would then auto scale the font size given in the model to meet the users current desired text size scale. Since we can't map directly between our builder font sizes and the iOS TextStyle options for scaling, we use a simple mapping for 3 scale levels - effectively small / medium / large, to give a reasonable result.
This change sets this option false by default, and removes the previous accidental text scaling on custom fonts. Previously, custom fonts would scale and system fonts would not. Now they both scale only when this option is enabled.
This example has a custom Lato-Black headline and then system text below. The OS setting is for a larger font size than the …
> Add support for text scaling

- Appcues.podspec
- Sources/AppcuesKit/Presentation/Extensions/Inits/NSDirectionalEdgeInsets+Style.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesSkippableTrait.swift
EAS builds via React Native pick up the DocC snippets as actual code to be compiled. This makes sure those files are excluded. 
Also, I noticed #420 missed the default margin for the skippable button was non-zero, so fixing that here too. Not sure why the Circle snapshot tests didn't catch that since running them locally did.
> Update podspec to exclude documentation snippets

- README.md
Right after I merged https://github.com/appcues/appcues-ios-sdk/pull/424 I realized I missed this one detail.
> Add link to new Anchored Tooltip section in index at top of README

- Sources/AppcuesKit/Appcues.swift
- Sources/AppcuesKit/AppcuesKit.docc/AppcuesKit.md
- Sources/AppcuesKit/Data/Models/Experience.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceRenderer.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine.swift
- Sources/AppcuesKit/Presentation/Extensions/UIView+Constrain.swift
- Sources/AppcuesKit/Presentation/Extensions/UIViewController+Embed.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesEmbeddedTrait.swift
- Sources/AppcuesKit/Presentation/Traits/TraitRegistry.swift
- Sources/AppcuesKit/Presentation/UI/AppcuesFrame.swift
- Sources/AppcuesKit/Presentation/UI/AppcuesFrameView.swift
- Tests/AppcuesKitTests/Experiences/EmbedExperienceRendererTests.swift
- Tests/AppcuesKitTests/PublicAPITests.swift
Nothing substantially different from what we've reviewed before (https://github.com/appcues/appcues-ios-sdk/pull/416).
I've polished up a few places, added first-class SwiftUI support, and some tests for the different scenarios we're supporting.
As we play around with this more (both in terms of different experience configurations, and different app configurations), there will be rough edges that need fixing up. For example, I already spent a bunch of time fixing an issue where the carousel trait wouldn't display properly in the SwiftUI frame.
> Add @appcues/embedded trait and AppcuesFrameView

- Examples/DeveloperCocoapodsExample/AppcuesCocoapodsExample.xcodeproj/project.pbxproj
- Examples/DeveloperCocoapodsExample/CocoapodsExample/Base.lproj/Main.storyboard
- Examples/DeveloperCocoapodsExample/CocoapodsExample/DeepLinkNavigator.swift
- Examples/DeveloperCocoapodsExample/CocoapodsExample/EmbedTestHarnessViewController.swift
- Examples/DeveloperCocoapodsExample/CocoapodsExample/EmbedViewController.swift
- Examples/DeveloperSPMExample/AppcuesSPMExample.xcodeproj/project.pbxproj
- Examples/DeveloperSPMExample/SPMExample/Base.lproj/Main.storyboard
- Examples/DeveloperSPMExample/SPMExample/DeepLinkNavigator.swift
- Examples/DeveloperSPMExample/SPMExample/EmbedTestHarnessViewController.swift
- Examples/DeveloperSPMExample/SPMExample/EmbedViewController.swift
Updating the SPM and Cocoapods examples with the Embed tab and a sub-page that can be launched from the button. The main page has 4 frames (frame1-frame4). The subpage allows toggling 2 frame (frame1, frame2) and will be useful for playing with the most complex sequences.
New `appcues-example://embed` deep link also added.
|Main tab|Button detail screen|
|-|-|
|![Simulator Screenshot - iPhone 14 Pro - 2023-07-11 at 14 26 35](https://github.com/appcues/appcues-ios-sdk/assets/845681/904cd693-9116-4637-9eec-dfac9be6c9ee)|![Simulator Screenshot - iPhone 14 Pro - 2023-07-11 at 14 26 38](https://github.com/appcues/appcues-ios-sdk/assets/845681/c36b1696-20b6-4a18-b737-c60169895ba7)|
> Update example apps with embed examples

- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesBackdropKeyholeTrait.swift
A value of 0 causes awkward transitions, so use `.leastNonZeroMagnitude` as a minimum value.
https://github.com/appcues/appcues-ios-sdk/assets/845681/4abba3ed-8e2f-4f1c-9d80-23f89bd381ed
https://github.com/appcues/appcues-ios-sdk/assets/845681/bc90434f-a6f3-4707-87a9-946b6670ec5d
> Set a minimum keyhole corner radius value

- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesCarouselTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesEmbeddedTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/ExperienceWrapperView.swift
- Sources/AppcuesKit/Presentation/UI/AppcuesFrameView.swift
Adjusting the embed trait to be container decorating addresses [an issue](https://appcues.slack.com/archives/C031RLGS4F8/p1692023469654459) where the frame position and size would appear wonkily. This is caused by an early call to the containerVC.view, which triggers viewDidLoad early and means there's a dropped content size update. This change works because `AppcuesWrapperCreatingTrait` gets called early in the trait composer vs `AppcuesContainerDecoratingTrait` which gets called later.
In all my playing around trying to resolve the above issue, I also finally addressed the spots we have the "min size 1" requirement. That requirement was caused by the carousel trait, and so the fix for it should be self contained in the carousel trait rather than having code everywhere (including in the …
> Fix embed rendering

- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceRenderer.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/StateMachineDirectory.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesCarouselTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesEmbeddedTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/ExperienceWrapperView.swift
- Sources/AppcuesKit/Presentation/UI/AppcuesFrame.swift
- Sources/AppcuesKit/Presentation/UI/AppcuesFrameView.swift
1. For the case where a FrameView(id: A) is registered and then a different FrameView(id: A) is registered. Now We call `reset()` for the first FrameView which removes the appcues content and removes the state machine without triggering any analytics. This essential resets the first FrameView back to how it was before it was registered. This is ideal because the newly registered second frame replaces the first in the state machine directory.
2. `AppcuesFrame` (the SwiftUI implementation) doesn't need the non-zero `preferredContentSize`, and having it created an additional gap in the layout.
3. EDIT: There's also the case where the same FrameView is registered for multiple IDs. Previously that meant the same StateMachineOwning would be in the directory for multiple RenderContexts, causing …
> Embed enhancements

- Sources/AppcuesKit/Appcues+Config.swift
- Sources/AppcuesKit/Appcues.swift
- Sources/AppcuesKit/Data/Analytics/AnalyticsPublisher.swift
- Sources/AppcuesKit/Data/Analytics/SessionMonitor.swift
- Sources/AppcuesKit/Presentation/Debugger/UIDebugger.swift
- Sources/AppcuesKit/Presentation/DeepLinkHandler.swift
- Tests/AppcuesKitTests/Analytics/SessionMonitorTests.swift
- Tests/AppcuesKitTests/AppcuesTests.swift
- Tests/AppcuesKitTests/MockAppcues.swift
Similar to what was done in https://github.com/appcues/appcues-android-sdk/pull/452, but thankfully less invasive here. Aligning on Appcues session definition per [doc](https://www.notion.so/appcues/The-definition-of-a-session-at-Appcues-bbaa1c717e9146fcadddaa4a96daea5c?pvs=4)
high level: remove session events for suspend/resume/reset - only track session_start. Update the timeout default to 300 sec (was 1800), and check for timeout after any period of analytics inactivity, regardless of app background/foreground. No longer track background/foreground at all effectively.
One update to the dependency graph - `AnalyticsPublishing` now uses `SessionMonitoring`, rather than the other way around. The red arrow here thus had its direction flipped ([link to final …
> Session handling updates

- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine.swift
- Sources/AppcuesKit/Presentation/Public/Plugins/AppcuesTraitError.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesTargetElementTrait.swift
- Tests/AppcuesKitTests/Traits/AppcuesTargetElementTraitTests.swift
This idea would support a `retryIntervals: [Int]?` on the trait config for the `@appcues/target-element` trait, which could optionally supply an array of millisecond delay values to support re-attempting trait application, if it failed with a `TraitError` due to a selector not being matched correctly. This could add more leniency for views that have animated loading or network bound loading that may affect the render performance when looking for an anchored element.
The default values would retry in certain failure scenarios at: 300ms, 900ms, 1800ms, and 3000ms, then report the standard step error if no target could be found after 3s. Having it in the trait config gives us server side control over these defaults, should we need in the future.
Not every type of failure would be retried - …
> Add retry capability for target element selector matching

- Examples/DeveloperCocoapodsExample/CocoapodsExample/Base.lproj/Main.storyboard
- Examples/DeveloperCocoapodsExample/CocoapodsExample/EventsViewController.swift
- Examples/DeveloperSPMExample/SPMExample/Base.lproj/Main.storyboard
- Examples/DeveloperSPMExample/SPMExample/EventsViewController.swift
Proposed idea to have a third button on the events page, which hides on initial render, then shows after two seconds. This allows for testing element targeting retry behavior recently introduced for delay loaded elements.
If we're happy with this idea, I can propagate to other test apps.
https://github.com/appcues/appcues-ios-sdk/assets/19266448/73f9856d-f8dc-4ce8-93f1-7eca5ab0942a
> Add delay loaded button to test element targeting retry

- Sources/AppcuesKit/Presentation/DeepLinkHandler.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceRenderer.swift
1. Making the error wording consistent.
2. There's no reason to have an array of experiences for a preview, so making that more explicit and optimized.
> Embed preview tweaks

- Sources/AppcuesKit/Appcues.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceRenderer.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/StateMachineDirectory.swift
- Tests/AppcuesKitTests/Experiences/ExperienceRendererTests.swift
- Tests/AppcuesKitTests/MockAppcues.swift
Building on the `reset()` function already available in `AppcuesFrameView`, I added `reset()` to the `StateMachineOwning` protocol. To conform to that, `ExperienceRenderer` removes the analytics listener and dismisses the experience held in its state machine. Then the new `ExperienceRendering.resetAll()` loops through the current state machines and and calls the `reset()` for each.
Finally, I updated the private `Appcues.identify()` (which includes `anonymous()`) to call `Appcues.reset()` when the user ID changes (instead of manually resetting values, since this missed the need to call the `.appcuesReset` notification for the debugger).
> Update ExperienceRenderer to reset on Appcues.reset()

- Sources/AppcuesKit/Presentation/UI/Components/AppcuesText.swift
Just in case an app has `""` as a localization key.
> Update text init to avoid inadvertant localization

- Sources/AppcuesKit/Presentation/Public/Plugins/AppcuesExperienceTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesEmbeddedTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesModalTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesTooltipTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/ExperienceWrapperSlideAnimator.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/ExperienceWrapperView.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/ExperienceWrapperViewController.swift
- Sources/AppcuesKit/Presentation/Traits/TraitComposer.swift
- Tests/AppcuesKitTests/Traits/AppcuesModalTraitTests.swift
- Tests/AppcuesKitTests/Traits/AppcuesTooltipTraitTests.swift
- Tests/AppcuesKitTests/Traits/ExperienceWrapperSlideAnimatorTests.swift
- Tests/AppcuesKitTests/Traits/TraitComposerTests.swift
Implements the slideout modal design using the model updates specified in https://github.com/appcues/appcues-mobile-experience-spec/pull/210
There was a little bit of constraint work, to allow for the dialog to have a width specified, and allow it to anchor to an edge of the screen rather than always the readable guide.
The bulk of the work was on the transition, in `ExperienceWrapperSlideAnimator`.  This involved some reading and learning about `UIViewControllerAnimatedTransitioning` on my part, and ended up following an approach adapted from some ideas found [here](https://devsign.co/notes/navigation-transitions-2).
Certainly open to any feedback and improvement on the animation details - I'm no expert. The 1 second entrance for the slide _felt_ about right to me. …
> Add slideout options to dialog modal presentation

- Sources/AppcuesKit/Presentation/ExperienceRendering/LifecycleEvent.swift
- Tests/AppcuesKitTests/Actions/AppcuesStepInteractionActionTests.swift
- Tests/AppcuesKitTests/Actions/AppcuesSubmitFormActionTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceStateMachine+AnalyticsObserverTests.swift
This is effectively a one line change to add `experienceInstanceId`, using our internal `instanceId` value, on each experience analytic event. This change allows the backend data system to distinctly tie together any events from one particular rendering of an experience, even if the same experience ID is shown multiple times.
Most of the changes here are to ensure that this new value is handled in analytics testing. There is also a change in `LifecycleEvent.EventProperties` to handle the new value in the structure used by the Debugger.
Related analytics UI test change over in https://github.com/appcues/appcues-ios-sdk/pull/414
> Add experienceInstanceId to experience analytics

- Sources/AppcuesKit/Data/Analytics/AnalyticsTracker.swift
- Sources/AppcuesKit/Data/Models/Activity.swift
- Tests/AppcuesKitTests/Analytics/ActivityProcessorTests.swift
- Tests/AppcuesKitTests/Analytics/AnalyticsTrackerTests.swift
- Tests/AppcuesKitTests/Networking/NetworkClientTests.swift
This approach has the `AnalyticsTracker` keep a reference to `Appcues` so that it can grab the session ID at the moment it translates a `TrackingUpdate` to `Activity`. There are a few ways we could do this. I think this is the smallest change, so starting here for any feedback.
Other possibilities:
1. Have the `TrackingUpdate` contain the session ID within. This could be done. There are six different classes that can create a `TrackingUpdate` currently, and most of those spots would need updated with handling to check for the session ID and pass through - somewhere along the line still checking for nil.
2. Update the `AnalyticsSubscriber.track(update)` function to also pass the session ID here, as second param - this would allow `AnalyticsPublisher`, which already has the `Appcues` …
> Add session_id to the root of activity/qualify API request body

- Sources/AppcuesKit/Appcues+Config.swift
- Sources/AppcuesKit/Data/Analytics/AnalyticsTracker.swift
- Sources/AppcuesKit/Data/Analytics/TrackingUpdate.swift
- Tests/AppcuesKitTests/Analytics/AnalyticsTrackerTests.swift
To make analytics queue processing testable, I moved the `private static flushAfterSeconds` to the `Config` object so I can modify it in the test. The test still takes 3s which is long for a unit test, but a lot better than waiting 11s.
Also added a couple tests that verify `AnalyticsTracker` calls `ExperienceRenderer` the way we think it does.
> Add test for analytics queuing and response handling

- Sources/AppcuesKit/Appcues+Config.swift
- Sources/AppcuesKit/Presentation/Debugger/Panel/DebugFontUI.swift
- Sources/AppcuesKit/Presentation/Debugger/Panel/DebugUI.swift
- Sources/AppcuesKit/Presentation/Debugger/Panel/DebugViewModel.swift
- Sources/AppcuesKit/Presentation/Debugger/UIDebugger.swift
- Tests/AppcuesKitTests/PublicAPITests.swift
The `Appcues.Config` function registers the fonts and saves the path for the debugger to reference.
I refactored the debugger font view a bit since the view shouldn't be responsible for determining the font list. So now the view model does.
> Add support for registering fonts from a bundle path

- Sources/AppcuesKit/Appcues+Config.swift
- Sources/AppcuesKit/Presentation/Debugger/Panel/DebugViewModel.swift
- Sources/AppcuesKit/Presentation/Debugger/UIDebugger.swift
- Tests/AppcuesKitTests/PublicAPITests.swift
Undoing the changes from https://github.com/appcues/appcues-ios-sdk/pull/457, but not strictly reverting, since there was some useful refactoring.
> Remove unneeded custom font registering

- Sources/AppcuesKit/AppcuesKit.docc/Tracking.md
It was pointed out that this doc doesn't show a SwiftUI example.
> Update screen tracking doc with SwiftUI example

- Sources/AppcuesKit/Data/Networking/Authorization.swift
- Sources/AppcuesKit/Presentation/Debugger/APIVerifier.swift
- Sources/AppcuesKit/Presentation/Debugger/DeepLinkVerifier.swift
- Sources/AppcuesKit/Presentation/Debugger/FloatingView/DebugViewController.swift
- Sources/AppcuesKit/Presentation/Debugger/Panel/DebugFontUI.swift
- Sources/AppcuesKit/Presentation/Debugger/Panel/DebugUI.swift
- Sources/AppcuesKit/Presentation/Debugger/Panel/DebugViewModel.swift
- Sources/AppcuesKit/Presentation/Debugger/Panel/LoggedEvent.swift
- Sources/AppcuesKit/Presentation/Debugger/Panel/StatusItem.swift
- Sources/AppcuesKit/Presentation/Debugger/Panel/StructuredLifecycleProperties.swift
- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/ScreenCapturer.swift
- Sources/AppcuesKit/Presentation/Debugger/Toasts/DebugToast.swift
- Sources/AppcuesKit/Presentation/Debugger/UIDebugger.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/LifecycleEvent.swift
- Tests/AppcuesKitTests/Analytics/AnalyticsBroadcasterTests.swift
- Tests/AppcuesKitTests/Debugger/APIVerifierTests.swift
- Tests/AppcuesKitTests/Debugger/DebugViewModelTests.swift
- Tests/AppcuesKitTests/Debugger/DeepLinkVerifierTests.swift
- Tests/AppcuesKitTests/Debugger/LoggedEventTests.swift
- Tests/AppcuesKitTests/Debugger/ScreenCapturerTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceLoaderTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceStateMachine+AnalyticsObserverTests.swift
- Tests/AppcuesKitTests/MockAppcues.swift
The debugger is undoubtedly (by far!) in the poorest shape of any part of the SDK codebase and is almost entirely untested. It's not a critical piece of the SDK, so that's not a huge problem, but with stuff like screen capture being increasingly important, it'd be worthwhile trying to make it better. This PR does some significant refactoring and adds a bunch of new tests.
1. Break up `DebugViewModel`. This >500 line file has a massive amount of stuff in it.
1. I've moved models like `StatusItem` and `LoggedEvent` to their own files.
2. I've created standalone classes `APIVerifier` and `DeepLinkVerifier` that encapsulate that functionality.
2. `DebugUI` now has views for each of the Status items. This better separates concerns and will make testing these in the future easier (all the tests …
> Debugger refactor

- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/Capture.swift
- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/SendCaptureUI.swift
Draw highlights (matching the mobile builder style) emphasizing the screenshot regions with selectors and add some help text if people aren't seeing the results they expect. The doc link is to https://docs.appcues.com/mobile-sdk-screen-capture-help which is a configurable redirect (so we can update it if the docs change).
|Some selectors|No selectors|
|-|-|
|![Simulator Screenshot - iPhone 14 Pro - 2023-10-18 at 15 18 51](https://github.com/appcues/appcues-ios-sdk/assets/845681/1aaa4b48-152f-4bfe-a5ec-4470285bb1d6)|![Simulator Screenshot - iPhone 14 Pro - 2023-10-18 at 15 18 46](https://github.com/appcues/appcues-ios-sdk/assets/845681/5fef7b69-6929-47a2-a285-16573efab2ad)|
> Add target overlay and help text to the screen capture confirm screen

- Examples/DeveloperCocoapodsExample/CocoapodsExample/EmbedTestHarnessViewController.swift
- Examples/DeveloperSPMExample/SPMExample/EmbedTestHarnessViewController.swift
Test app update that lets us identify a user from the embed test harness. Merging this before the re-render fix so we can verify the bug and fix in the TestFlight app.
> Add identify to example embed options

- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceRenderer.swift
- Tests/AppcuesKitTests/Experiences/ExperienceRendererTests.swift
Sibling to https://github.com/appcues/appcues-android-sdk/pull/519 (and PR description shameless stolen)
Scenario:
- embed is triggered on session start (event trigger) and placed in cache
- later gets rendered ok
- another analytic occurs (i.e. identify, not a screen)
- no new experiences, and no cache clear, cache is re-processed
- the experience in cache tries to re-render by dismissing the current experience and re-starting --> not desired
We only want to dismiss the current experience if (1) it is a new experience from the server of normal priority (not a screen view) or (2) it is an updated version of the current experience from server (new instance id)
> 🐛 Do not dismiss and re-render an experience with the same instance from cache

- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/SendCaptureUI.swift
- Tests/AppcuesKitTests/Experiences/ExperienceRendererTests.swift
Also noticed yesterday when updating the ExperienceRenderer tests that they were using a weird waiting syntax, but didn't want to pollute the diff there. Updating that syntax now.
> Ensure screen capture cancel button is visible in dark mode

- Sources/AppcuesKit/Data/Analytics/AutoPropertyDecorator.swift
- Tests/AppcuesKitTests/Analytics/AutoPropertyDecoratorTests.swift
Removing this auto property on iOS for performance reasons: the user agent value was determined at SDK init and must be on the main thread because it uses a UIKit view.
It is not believed to be a useful property in mobile for most scenarios, and it can be sent as a custom property if still desired for targeting content.
Sibling of https://github.com/appcues/appcues-android-sdk/pull/520
> Remove _userAgent auto property

- Sources/AppcuesKit/Appcues.swift
- Sources/AppcuesKit/Data/Analytics/AnalyticsTracker.swift
- Sources/AppcuesKit/Data/Logging/OSLog+Convenience.swift
- Sources/AppcuesKit/Data/Models/Activity.swift
- Sources/AppcuesKit/Data/Models/Event.swift
- Sources/AppcuesKit/Data/Networking/DynamicCodingKeys.swift
- Sources/AppcuesKit/Presentation/Actions/ActionRegistry.swift
- Sources/AppcuesKit/Presentation/Traits/TraitRegistry.swift
- Tests/AppcuesKitTests/Actions/ActionRegistryTests.swift
- Tests/AppcuesKitTests/Traits/TraitRegistryTests.swift
To be as safe as possible, remove places where `assertionFailure` would cause a crash in `-Onone` debug builds (https://developer.apple.com/documentation/swift/assertionfailure(_:file:line:)).
To not lose the message when encoding properties, I'm passing the logging instance through to the encoder from the `Activity` and `Event` models. I'm not the biggest fan of doing this, but I think it's worthwhile (and the parameter is optional).
I have a subsequent PR lined op that makes a generic `Logging` protocol that will let us intercept the logs to show in the debugger and test the log messages that get generated.
> Remove assertionFailures

- Sources/AppcuesKit/Appcues+Config.swift
- Sources/AppcuesKit/Appcues.swift
- Sources/AppcuesKit/Data/Analytics/AnalyticsTracker.swift
- Sources/AppcuesKit/Data/Logging/Logging.swift
- Sources/AppcuesKit/Data/Models/Activity.swift
- Sources/AppcuesKit/Data/Models/Event.swift
- Sources/AppcuesKit/Data/Networking/DynamicCodingKeys.swift
- Sources/AppcuesKit/Data/Networking/NetworkClient.swift
- Sources/AppcuesKit/Presentation/Debugger/DebugLogger.swift
- Sources/AppcuesKit/Presentation/Debugger/FloatingView/DebugViewController.swift
- Sources/AppcuesKit/Presentation/Debugger/Panel/DebugLogUI.swift
- Sources/AppcuesKit/Presentation/Debugger/Panel/DebugUI.swift
- Sources/AppcuesKit/Presentation/Debugger/UIDebugger.swift
- Sources/AppcuesKit/Presentation/ExperienceLoader.swift
- Tests/AppcuesKitTests/Actions/ActionRegistryTests.swift
- Tests/AppcuesKitTests/Networking/DynamicCodingKeysTests.swift
- Tests/AppcuesKitTests/Traits/TraitRegistryTests.swift
I used %s for the original logs without much thought (copied from some blog post IIRC), and it worked, but for mapping to an actual string, %@ is the way to go, so fixed that ([format string reference](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Strings/Articles/formatSpecifiers.html)). We have to strip out the `{public}` and `{private}` OSLog specifiers, but then we can get the log message as a regular String to show in the debugger.
Then the new `Logging` protocol has conformees in `OSLog` and the new `DebugLog` so we can transparently switch between them. `DebugLog` even optionally takes another `Logging` instance so we can continue to send the `OSLog` messages in addition to capturing them in the debugger.
The debug logger only starts when the debugger …
> Add log viewing to debugger

- Sources/AppcuesKit/Data/Analytics/AutoPropertyDecorator.swift
- Sources/AppcuesKit/Data/Models/Activity.swift
- Tests/AppcuesKitTests/Analytics/AutoPropertyDecoratorTests.swift
Also [sc-58902]
```diff
{
+	"source": "mobile",
"account_id": "<account-id>",
"group_id": "my-group",
"request_id": "fc592fd8-9210-463b-a73d-c4b19dcfe454",
"session_id": "1b554130-1d90-4969-8a1d-56e7a877ef11",
"user_id": "default-00000",
"group_update": {
+		"_lastSeenAt": 1699296009124
}
}
```
> Add source to activity requests and  _lastSeenAt group auto prop

- Sources/AppcuesKit/Data/Analytics/AnalyticsTracker.swift
- Sources/AppcuesKit/Data/Analytics/AutoPropertyDecorator.swift
- Sources/AppcuesKit/Data/Analytics/TrackingUpdate.swift
- Sources/AppcuesKit/Data/Models/Activity.swift
- Tests/AppcuesKitTests/Analytics/AnalyticsTrackerTests.swift
This is the iOS equivalent of the Android update in https://github.com/appcues/appcues-android-sdk/pull/535 (and similar in concept to the web update in https://github.com/appcues/javascript-sdk/pull/613). Stealing that Android PR description:
* on `identify(id, props)` or the `appcues:session_started` event - a 50ms timer is started to allow analytics that occur immediately after, to be batched together into the same activity payload to the API.
* the expected use case would be a `group(id, props)` called immediately after `identify(id, props)` resulting in a combined payload with the new user and the current group - this prevents any chance of state group information being used during the resulting qualification on the server for the new user update or session start qualification
* all …
> Batch group updates with user identification when called right after identify

- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceRenderer.swift
Noticed this bug in the showcase app. Signing out (ie calling `Appcues.reset()`) would crash, because it was trying to do UI operations on a background thread. The operations in question are resetting embed frames. So I've added our standard main thread check to `ExperienceRenderer.resetAll()` and that fixes it.
> Ensure resetting embed frames happens on main thread

- Sources/AppcuesKit/Presentation/Extensions/UIViewController+Embed.swift
- Sources/AppcuesKit/Presentation/UI/AppcuesFrame.swift
- Sources/AppcuesKit/Presentation/UI/AppcuesFrameView.swift
Margins work properly for the UIKit implementation of embeds, but not SwiftUI, React Native, and Flutter. Why? Each of the broken options wrap the `AppcuesFrameView` in a `UIViewController` and set the content size according to the `preferredContentSize` of that `UIViewController`.
The margins on an embed were being set by way of `constant` values on constraints. The `AppcuesFrameView` had a child view that constrained to be inset by the margins. The issue is that the `preferredContentSize` that gets reported up the view controller chain doesn't include these margin values which are outside the frame of the `UIViewController.view`.
So for example, if the preferredContentSize is 300x150 and there's 10px margins, the total frame size should be 320x170, but instead the margins were getting …
> Ensure FrameView margins are added to the content size to avoid unnecessary scrolling

- Sources/AppcuesKit/Presentation/Traits/Appcues/ExperienceWrapperSlideAnimator.swift
When a view controller is presented with `UIModalPresentationStyle.overFullScreen`, that results in the following constraints:
We were using our `.pin(...)` extension which sets top/left/right/bottom constraints, but crucially doesn't say anything about the dimensions of the view. So when the constraints are recalculated, you can end up with something sized to the slideout, not the window:
I expected that setting height and width constraints would do the trick, but for some reason it doesn't.
```swift
NSLayoutConstraint.activate([
toView.heightAnchor.constraint(equalTo: transitionContext.containerView.heightAnchor),
toView.widthAnchor.constraint(equalTo: transitionContext.containerView.widthAnchor)
])
```
I guess it doesn't work because the `UITransitionView` doesn't have a fixed …
> Update slideout constraints to match the standard UIKit approach

- Sources/AppcuesKit/Appcues.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/ExperienceWrapperViewController.swift
Running the flutter objc workspace noted the incorrect parameter name and I noticed the bad whitespace looking at the slideout issue yesterday.
> 2 tiny random things

- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/UIKitElementTargeting.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceRenderer.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/StepRecoveryObserver.swift
- Sources/AppcuesKit/Presentation/Extensions/UIScrollView+ScrollObserver.swift
- Tests/AppcuesKitTests/Traits/AppcuesTargetElementTraitTests.swift
These are the updates that stack on top of state machine updates in #474 to address the specific use case of anchored tooltips that scroll into view.
Most of the code here is the swizzling details for UIScrollView. Those updates effectively watch for `scrollViewDidEndDecelerating` and `scrollViewDidEndDragging` calls to determine when a scroll view in the host application may have come to "rest". This "rest" is defined as 1 sec elapsing after those updates without any additional `scrollViewDidScroll` occurring. This logic _should_ also protect against typical scroll "bounce" at top/bottom that can occur - we do not want to identify a target rect during the bounce, as it will be offset from the eventual resting place of that view.
There are multiple scenarios to handle in swizzling related …
> Add capability to listen for scroll changes and attempt to recover a tooltip from step error

- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/UIKitElementTargeting.swift
- Sources/AppcuesKit/Presentation/DeepLinkHandler.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceRenderer.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine+Action.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine+ExperienceError.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine+State.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateObserver.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/StepRecoveryObserver.swift
- Sources/AppcuesKit/Presentation/Extensions/UIScrollView+ScrollObserver.swift
- Sources/AppcuesKit/Presentation/Public/Plugins/AppcuesTraitError.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesTargetElementTrait.swift
- Tests/AppcuesKitTests/Experiences/ExperienceStateMachine+AnalyticsObserverTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceStateMachineTests.swift
- Tests/AppcuesKitTests/Traits/AppcuesTargetElementTraitTests.swift
The work here is analogous to what is being worked on the Android side in https://github.com/appcues/appcues-android-sdk/pull/528.
At a high level: an `AppcuesTraitError` can be marked as `recoverable`. A `.step` error resulting from this can then instruct the state machine to go into a new `.failing` state, rather than being considered fatal, as before. When in the `.failing` state, a `.retry` action can trigger another attempt to move to the desired target state (the state of the transition when it failed previously), and retry some `SideEffect` (as of now, always the container presentation).
If the step is able to recover and present successfully, it moves back into the normal state machine flow (.renderingStep) and an `appcues:v2:step_recovery` analytics event is generated, with a …
> Add support for step error handling and recovery

- Sources/AppcuesKit/Utilities/DIContainer.swift
- Tests/AppcuesKitTests/AppcuesTests.swift
As reported on our RN SDK (https://github.com/appcues/appcues-react-native-module/issues/128), we can get crashes in `DIContainer` from a lack of thread safety:
```
EXC_BAD_ACCESS: Attempted to dereference garbage pointer 0x8000000000000008.
0  libswiftCore.dylib +0x400034    _swift_isUniquelyReferenced_nonNull_native
1  Redacted +0xc77b0               specialized Dictionary._Variant.isUniquelyReferenced() (<compiler-generated>)
2  Redacted +0x25298               specialized Dictionary.subscript.setter (<compiler-generated>)
3  Redacted +0x24580               specialized DIContainer.resolve<A>(_:) (<compiler-generated>)
4  Redacted +0x25814               specialized DIContainer.resolve<A>(_:)
5  Redacted +0x158e7c              specialized DIContainer.resolve<A>(_:) (<compiler-generated>) …
```
> Fix crash from lack of thread safety in DIContainer

- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/UIKitElementTargeting.swift
- Tests/AppcuesKitTests/Traits/AppcuesTargetElementTraitTests.swift
Discovered in testing / prepping a demo - in some cases an invalid intersection rect can be returned in the check with the safe area bounds, resulting in a layout object with values that cannot be serialized to JSON correctly, and fail upload. This new check will prevent that.
> Guard against an invalid view rect in screen capture

- Sources/AppcuesKit/AppcuesKit.docc/Identifying.md
Per recent customer feedback and [discussion](https://appcues.slack.com/archives/C031RLGS4F8/p1704495749255789) - moving to an approach where we do not provide a code snippet including `"appcues:user_id_signature"` that could mistakenly be copy/pasted, and rather a less explicit pointer to the main help doc for identity verification - for the less common use case where those details are needed.
> Update identity verification note to point to central help doc

- Sources/AppcuesKit/Presentation/Actions/Appcues/AppcuesTrackAction.swift
- Tests/AppcuesKitTests/Actions/AppcuesStepInteractionActionTests.swift
- Tests/AppcuesKitTests/Actions/AppcuesTrackActionTests.swift
This is part of a larger initiative for integrations related to button clicks, on our end for now we need to add an attribute property that can receive generic information from builder, and pass it as properties when calling appcues.track internally.
> ✨ Adding config.attributes to action @appcues/track

- Sources/AppcuesKit/Appcues.swift
- Sources/AppcuesKit/Data/Networking/Endpoint.swift
- Sources/AppcuesKit/Presentation/Actions/Appcues/AppcuesLaunchExperienceAction.swift
- Sources/AppcuesKit/Presentation/DeepLinkHandler.swift
- Sources/AppcuesKit/Presentation/ExperienceLoader.swift
- Tests/AppcuesKitTests/Experiences/ExperienceLoaderTests.swift
- Tests/AppcuesKitTests/MockAppcues.swift
Proposing an idea here, not sold on it - but this one would allow us to take any set of additional query parameters on the `/experience_preview` or `/experience_content` SDK deep links. This would be used to support a new `?locale_id={id}` parameter during the QR code preview flow from the builder. This approach is more generic, where it would just take any set of params given and pass them through, verbatim, to the api request that gets made.
The more specific approach would be to simply read the one `locale_id` param on the preview call directly, and use that in only the preview call. I thought perhaps a more general approach here would let us possibly add other things in the future without SDK changes. The more I think about it, it seems like YAGNI and I'm not happy with the change …
> Support additional query parameters on deep links to preview or show experiences

- Sources/AppcuesKit/Presentation/Debugger/Panel/DebugUI.swift
Went with a long press context menu to
1) avoid accidental copies
2) match the `ListItemRowView` in the debugger
> Add long press to copy to debugger values

- Sources/AppcuesKit/Appcues.swift
- Sources/AppcuesKit/AppcuesKit.docc/Extensions/Appcues.md
- Sources/AppcuesKit/Data/Analytics/AutoPropertyDecorator.swift
- Sources/AppcuesKit/Data/Networking/DynamicCodingKeys.swift
- Sources/AppcuesKit/Data/Storage.swift
- Tests/AppcuesKitTests/Analytics/AutoPropertyDecoratorTests.swift
- Tests/AppcuesKitTests/AppcuesTests.swift
- Tests/AppcuesKitTests/MockAppcues.swift
- Tests/AppcuesKitTests/PublicAPITests.swift
Used the format `%02x` (vs [`%02.2hhx`](https://github.com/appcues/appcues-ios-sdk/blob/ca6ffb8894d425557ad1be9ca03cd126d5a50e0c/Sources/AppcuesKit/Appcues.swift#L314C56-L314C64)) according to https://nshipster.com/apns-device-tokens/
We haven't had a case where we explicitly want to pass a null value through the properties, so I needed to add encoding support for `NSNull`.
Also [sc-60904]
> Add Appcues.setPushToken and _pushToken device property

- Sources/AppcuesKit/Data/Networking/NetworkClient.swift
- Sources/AppcuesKit/Data/Networking/NetworkingError.swift
Ensure that a helpful response is always logged. Previously if there was no HTTP status code, we'd not get a log which makes debugging extra tricky. Now we always log _something_, and add the `error` body and empty message if those conditions would cause the response decode to fail.
Also, in the case where `data == nil`, we were returning without calling the completion handler, which, while unlikely, is bad, so I added an error completion block there too.
Now we can get something like this, instead of nothing, which is a big improvement.
> Improve network logging

- Sources/AppcuesKit/Data/Analytics/AnalyticsPublisher.swift
- Sources/AppcuesKit/Data/Analytics/AutoPropertyDecorator.swift
- Sources/AppcuesKit/Data/Analytics/SessionMonitor.swift
- Sources/AppcuesKit/Data/Analytics/TrackingUpdate.swift
- Sources/AppcuesKit/Data/Events.swift
- Sources/AppcuesKit/Presentation/Actions/Appcues/AppcuesStepInteractionAction.swift
- Sources/AppcuesKit/Presentation/Actions/Appcues/AppcuesSubmitFormAction.swift
- Sources/AppcuesKit/Presentation/Debugger/Panel/LoggedEvent.swift
- Sources/AppcuesKit/Presentation/Debugger/Panel/StructuredLifecycleProperties.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/Dictionary+ExperienceProperties.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateObserver.swift
This is some refactoring targeting `main` before adding the new device events in the `sdk4` branch. Basically, I don't like that currently,
1) event names are scattered in different places (manifests the question, "where do I put the new device event names"), and
2) the name `LifecycleEvent` always confused me when I was looking for them.
Now there's `enum Events` which namespaces `Session` and `Experience` (and soon `Device`). This seems substantially more friendly to anyone new to the codebase.
Also in the name of clarity, I replaced the strange static extension `LifecycleEvent.properties()` with a `Dictionary` initializer.
Last little change was renaming `func trackLifecycleEvent(_ name: LifecycleEvent, _ properties: [String: Any])` to `func track(experienceEvent name: …
> Centralize analytic event names

- Sources/AppcuesKit/Data/Analytics/AnalyticsPublisher.swift
- Sources/AppcuesKit/Presentation/Actions/Appcues/AppcuesStepInteractionAction.swift
- Sources/AppcuesKit/Presentation/Actions/Appcues/AppcuesSubmitFormAction.swift
- Sources/AppcuesKit/Presentation/Debugger/DebugLogger.swift
- Sources/AppcuesKit/Presentation/Debugger/Panel/DebugLogUI.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateObserver.swift
- Tests/AppcuesKitTests/Actions/AppcuesStepInteractionActionTests.swift
- Tests/AppcuesKitTests/Actions/AppcuesSubmitFormActionTests.swift
- Tests/AppcuesKitTests/Analytics/AnalyticsPublisherTests.swift
- Tests/AppcuesKitTests/MockAppcues.swift
- Tests/AppcuesKitTests/Mocks.swift
1. Update `AnalyticsPublisher` to be able to conditionally publish or debug log analytics
- `decorateAndPublish()` got split into `decorate()` and `notifySubscribers()` so that the logging path can also decorate
2. Log experience analytics for flow previews instead of doing nothing
3. Log action analytics with `@appcues/step_interaction` and `@appcues/submit-form` for flow previews instead of publishing
4. Add a share sheet link to the debugger to allow easy sharing (or copying) the entire debug log
5. New tests
> Ensure actions with analytics log instead of publish for experience previews

- Sources/AppcuesKit/Appcues.swift
- Sources/AppcuesKit/Data/Analytics/AutoPropertyDecorator.swift
- Sources/AppcuesKit/Data/PushMonitor.swift
- Tests/AppcuesKitTests/Analytics/AutoPropertyDecoratorTests.swift
- Tests/AppcuesKitTests/MockAppcues.swift
- Tests/AppcuesKitTests/PushMonitorTests.swift
I created a new `PushMonitor` dependency, mostly because of the requirement to watch for new foreground events—it felt weird to have that happening in the `AutoPropertyDecorator`, or anywhere else non-specific. Push handlers and other stuff might end up in `PushMonitor` (and necessitate a rename) in the future, but I haven't really planned that out yet.
The non-straightforward part of this is that calls to `UNUserNotificationCenter` crash in tests for non-app targets ([Stack Overflow](https://stackoverflow.com/questions/77448766/app-crashes-when-im-getting-unusernotificationcenter-current-from-into-a-swif)). Because there are tests that use `Appcues` in addition to `MockAppcues`, we can't use `UNUserNotificationCenter` without doing something different in the SDK code when tests are …
> Add push status device properties

- Sources/AppcuesKit/Data/Models/Experience.swift
- Sources/AppcuesKit/Presentation/Actions/Appcues/AppcuesLaunchExperienceAction.swift
This is a little side quest as I'm implementing push handlers, but I want to keep refactoring on the `main` branch.
The previous `init(appcues: Appcues?, renderContext: RenderContext, experienceID: String, trigger: ExperienceTrigger)` required a `renderContext` value for which there's no proper value when initing from the push handler. That code smell made me look closer and it turns out storing `renderContext` was unnecessary because there’s never a case where it would be used when `trigger` is specified, and `renderContext` was only used to compute a fallback trigger value.
The required change is simply computing the proper `trigger` of `.launchExperienceAction` in the `init` using the `renderContext` of `AppcuesExperiencePluginConfiguration`, instead of storing `renderContext` to use …
> Simplify launch experience action implementation

- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine.swift
- Sources/AppcuesKit/Presentation/UI/AppcuesFrameView.swift
Only `experienceWillDisappear()` was working properly.
`experienceWillAppear()` and `experienceDidAppear()` weren't being called because we were only checking `isBeingPresented` (which works for modals/tooltips) and not also `isMovingToParent`. I cleaned all the checks up with a simpler extension.
`experienceDidDisappear()` wasn't working because the state machine reaches the `.idling` state before `containerDidDisappear` gets called. This is essentially because the `completion()` for the dismisser of the embed gets called too early. There's nothing logically wrong with where it's called, but `DispatchQueue.main.async` fixes it. Alternatively, I could've added a case for `.idling` in `containerDidDisappear` but that could have wider ranging side effects an would be specific to embeds, …
> Fix AppcuesExperienceDelegate for embeds

- Examples/DeveloperCocoapodsExample/AppcuesCocoapodsExample.entitlements
- Examples/DeveloperCocoapodsExample/AppcuesCocoapodsExample.xcodeproj/project.pbxproj
- Examples/DeveloperCocoapodsExample/CocoapodsExample/AppDelegate+Push.swift
- Examples/DeveloperCocoapodsExample/CocoapodsExample/AppDelegate.swift
- Examples/DeveloperCocoapodsExample/CocoapodsExample/Info.plist
- Examples/DeveloperCocoapodsExample/Podfile.lock
- Examples/DeveloperCocoapodsExample/project.yml
- Sources/AppcuesKit/Presentation/Actions/ActionRegistry.swift
I put as much of the push stuff in `AppDelegate+Push` as possible and tried to structure it nicely so it can function as a reference.
Result of a [test push](https://icloud.developer.apple.com/dashboard/notifications/teams/KHSQ25769M/app/com.appcues.sdk-example-cocoapods/notifications/78bb2541-9e38-4dc5-9bd8-ba12742e1ea5/environment/DEVELOPMENT/tracking/dbbbbe12-64ce-2f0a-88ff-38feed577013) from the console :tada:
> Configure cocoapods example app for push

- Sources/AppcuesKit/Presentation/Actions/Appcues/AppcuesLinkAction.swift
Log a different message for each possible case:
> Add link action logging

- Sources/AppcuesKit/Appcues.swift
- Sources/AppcuesKit/Data/Networking/Endpoint.swift
- Sources/AppcuesKit/Presentation/Debugger/FloatingView/DebugViewController.swift
- Sources/AppcuesKit/Presentation/Debugger/Panel/DebugUI.swift
- Sources/AppcuesKit/Presentation/Debugger/PushVerifier.swift
- Sources/AppcuesKit/Presentation/Debugger/UIDebugger.swift
- Sources/AppcuesKit/Push/ParsedNotification.swift
- Sources/AppcuesKit/Push/PushMonitor.swift
- Tests/AppcuesKitTests/MockAppcues.swift
I've been able to create a surprisingly full-featured push verification system for the debugger. And once we hook it up to the send test push API that can return some backend diagnostics, we should be able to provide one-tap E2E verification of an Appcues push setup.
`PushVerifier` is the doing all the heavy lifting. Since it has several dependencies and since `PushMonitor` needs to call the verifier, I've added it into the main DI container unlike `APIVerifier` and `DeepLinkVerifier`.
Overview of what's being verified (and how), corresponding to the Error numbers:
1. Verify `Appcues.setPushToken(:)` is called. I could add an additional check that `didRegisterForRemoteNotificationsWithDeviceToken` is implemented, but these are tightly coupled, so it seems like overkill. The docs (when we …
> Add push install verification to debugger

- Sources/AppcuesKit/Appcues.swift
- Sources/AppcuesKit/Presentation/Debugger/Panel/DebugLogUI.swift
- Sources/AppcuesKit/Push/PushMonitor.swift
- Tests/AppcuesKitTests/MockAppcues.swift
- Tests/AppcuesKitTests/Push/PushMonitorTests.swift
Also adding a basic search bar to the debug log
Edit: and now that I've figured out we can mock `UNNotificationResponse` in tests, I've updated `PushMonitor.didReceiveNotification(response: UNNotificationResponse, completionHandler: @escaping () -> Void) -> Bool` to take the full response object instead of just the `userInfo`. We'll need it for the `response.actionIdentifier` and other stuff in the future.
> Add push action handler logging

- Sources/AppcuesKit/Presentation/Actions/Appcues/AppcuesRequestPushAction.swift
- Sources/AppcuesKit/Presentation/Debugger/PushVerifier.swift
- Sources/AppcuesKit/Push/PushMonitor.swift
- Tests/AppcuesKitTests/Actions/AppcuesRequestPushActionTests.swift
- Tests/AppcuesKitTests/MockAppcues.swift
Per [discussion](https://app.shortcut.com/appcues/story/62368/implement-appcues-device-updated-event#activity-63884), when the app is foregrounded, the push status refresh should send a `appcues:device_updated` event if the status changed.
I've moved the `appcues:device_updated` event out of the request push action and now it can be triggered with the `publishChange` argument.
> Send device_updated event on push status change

- Sources/AppcuesKit/Appcues.swift
- Sources/AppcuesKit/Push/PushMonitor.swift
- Tests/AppcuesKitTests/AppcuesTests.swift
- Tests/AppcuesKitTests/MockAppcues.swift
- Tests/AppcuesKitTests/Push/PushMonitorTests.swift
The flow is pretty simple:
1. If we receive a push response and appcues isn't active, store the `ParsedNotification`.
2. On any `identify` call, attempt the deferred notification response.
1. The sequence of analytics is session started, identify, push opened
2. `attemptDeferredNotificationResponse` returns a boolean which isn't currently used apart from tests. In theory it could easily have a completion handler. It's something we might need to deal with if we find the push response handling colliding with other things happening on session start or after a sign in
> Add deferred handling for push notifications received without a session

- Sources/AppcuesKit/Push/ParsedNotification.swift
- Sources/AppcuesNotificationService/AppcuesNotificationServiceExtension.swift
Removing the requirement for `appcues_attachment_type`.
`URLSession.downloadTask(with:completionHandler:)` is almost as easy as `Data(contentsOf:)`. It creates a download task that saves the results to a file which we can copy to our attachment with the mime type of the `URLResponse`. Using `UTType` means we don't need a hardcoded map of mime types to file extensions (even if the pre-ios 14 fallback is a bit ugly).
> Determine push attachment file type using file mime type

- Sources/AppcuesKit/Presentation/Debugger/Panel/DebugUI.swift
- Sources/AppcuesKit/Presentation/Debugger/PushVerifier.swift
I missed that the push debugger now needs the account/app ID values set after the changes in #523.
And I saw https://github.com/appcues/appcues-android-sdk/pull/589 which made me realize we can open the app settings in the case where push permissions are denied to make it easy to unblock that issue.
> Push debugger enhancements

- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine.swift
- Tests/AppcuesKitTests/Experiences/ExperienceStateMachineTests.swift
- Tests/AppcuesKitTests/Mocks.swift
I was debugging the memory graph for some push stuff and noticed that our experience-related objects were sticking around after an experience completes. I verified this wasn't an `sdk4` issue, so here we are.
This one was a bit confusing, and I honestly don't fully understand why it was an issue, but the `ExperiencePackage` owns the `AppcuesExperiencePageMonitor`, but then the page monitor observer list was holding a reference to the package/state machine side effect. We have `weak package` already which I'd have expected to take care of the problem, but it turns out that the call to `SideEffect.handlePresentationError()` was the culprit.
If I inlined the contents of `handlePresentationError()`, the retain cycle disappeared. And the standard `weak self` to try and do …
> Fix memory leak when presenting an experience

- Examples/DeveloperCocoapodsExample/CocoapodsExample/AppDelegate.swift
- Sources/AppcuesKit/Appcues.swift
- Sources/AppcuesKit/Push/PushAutoConfig.swift
- Sources/AppcuesKit/Push/PushMonitor.swift
- Sources/AppcuesKit/Push/UIApplication+AutoConfig.swift
- Sources/AppcuesKit/Push/UNUserNotificationCenter+AutoConfig.swift
This is a tweak targeting #526 in its own PR for readability. I've made the swizzling automatic push config static on `Appcues` for a couple reasons:
1. Swizzling affects the whole app, not just the instance. So in the theoretical multiple Appcues instance app, it'd be very strange to suggest that you could automatically configure one instance but not the other.
2. A static config option better sets us up for x-plat success. More [here](https://appcues.slack.com/archives/C031RLGS4F8/p1712932756018019), but since the x-plat libraries create the `Appcues` instance on-demand, that may be too late for the config necessary in `didFinishLaunching`.
The static observer list pattern I've added means that,
1. If an `Appcues` instance is created before the push auto config, then it's already in the …
> Update push auto config to be static

- Examples/DeveloperCocoapodsExample/CocoapodsExample/AppDelegate+Push.swift
- Examples/DeveloperCocoapodsExample/CocoapodsExample/AppDelegate.swift
- Sources/AppcuesKit/Appcues.swift
- Sources/AppcuesKit/Presentation/Extensions/UIScrollView+ScrollObserver.swift
- Sources/AppcuesKit/Push/PushAutoConfig.swift
- Sources/AppcuesKit/Push/PushMonitor.swift
- Sources/AppcuesKit/Push/UIApplication+AutoConfig.swift
- Sources/AppcuesKit/Push/UNUserNotificationCenter+AutoConfig.swift
- Sources/AppcuesKit/Utilities/Swizzler.swift
- Tests/AppcuesKitTests/AppcuesTests.swift
- Tests/AppcuesKitTests/MockAppcues.swift
- Tests/AppcuesKitTests/Push/PushMonitorTests.swift
This PR is very much building on the approach for the `UIScrollViewDelegate` swizzling added and explained in  https://github.com/appcues/appcues-ios-sdk/pull/479.
As noted in the `Appcues.swift` docs, there's 5 things that need to happen for automatic push config:
1. Calling `UIApplication.registerForRemoteNotifications()`.
- This is straightforward.
2. Implementing `UIApplicationDelegate.application(_:didRegisterForRemoteNotificationsWithDeviceToken:)` to call `Appcues.setPushToken(_:)`.
- Because we can safely assume there's always a `UIApplicationDelegate`, we just need to add the placeholder implementation if there is none, and then swizzle the method.
3. Ensuring `UNUserNotificationCenter.current().delegate` is set.
- This is the same approach as the `UIScrollViewDelegate` getter …
> Add one line push config

- Sources/AppcuesKit/Presentation/Debugger/FloatingView/DebugUIWindow.swift
Take two on 8426b9ac (#525). The first approach didn't account for a presented view controller (eg the screen capture confirm dialog) nor system menus.
> Fix debugger hit test on iPad

- Sources/AppcuesKit/Presentation/ContentLoader.swift
Warning `immutable value 'experience' was never used` was causing cocoapods to fail to publish. I've temporarily bypassed with `--allow-warnings`, but this fixes it for next time.
Also ensuring the completion callback is called. Didn't matter yet, but it will for push error handling.
> Fix lint warning

- Examples/DeveloperCocoapodsExample/Podfile.lock
- Sources/AppcuesKit/Data/Networking/NetworkClient.swift
- Sources/AppcuesKit/Presentation/DeepLinkHandler.swift
- Sources/AppcuesKit/Push/PushMonitor.swift
- Tests/AppcuesKitTests/Push/PushMonitorTests.swift
Gives some immediate feedback if something went wrong on the push preview request, similar to flow preview issues.
Also, now provides error detail in the detailed log with the response body error messages to troubleshoot. (note: some work going in api/pushserv soon to improve a few cases here to be more helpful)
> Add push preview error feedback toast

- Sources/AppcuesKit/Data/Analytics/AutoPropertyDecorator.swift
- Sources/AppcuesKit/Presentation/Debugger/PushVerifier.swift
- Sources/AppcuesKit/Push/PushEnvironment.swift
- Sources/AppcuesKit/Push/PushMonitor.swift
- Tests/AppcuesKitTests/Analytics/AutoPropertyDecoratorTests.swift
- Tests/AppcuesKitTests/MockAppcues.swift
Add a `_pushEnvironment` device auto property with a value of `development` or `production`. The value starts as unknown (which tracks as `production`) until a background thread can read and parse the provisioning profile data, if it's available.
There's a few options here:
1. No `embedded.mobileprovision`. This could be a simulator build ( so want `development`) or an App Store one (`production`):
> App Store apps do not contain an embedded provisioning profile because the App Store checks that the app is signed and provisioned correctly as part of its app ingestion process.
- https://developer.apple.com/documentation/technotes/tn3125-inside-code-signing-provisioning-profiles#Profile-location
2. There is an `embedded.mobileprovision`. This could a development build (`development`) or an …
> Add support for automatic push environment detection

- Sources/AppcuesKit/Presentation/Actions/Appcues/AppcuesRequestPushAction.swift
- Sources/AppcuesKit/Presentation/Debugger/PushVerifier.swift
- Sources/AppcuesKit/Push/PushMonitor.swift
- Tests/AppcuesKitTests/Actions/AppcuesRequestPushActionTests.swift
- Tests/AppcuesKitTests/MockAppcues.swift
- Tests/AppcuesKitTests/Push/PushMonitorTests.swift
James [noted](https://appcues.slack.com/archives/C031RLGS4F8/p1717616763921679) a while back that there can be a race where `pushEnabled` is read and sent to the backend at startup before the correct value can be determined.
To fix this, we want to make sure the initial request for the permission status will send a device updated event if the value is different than the one that was used. This initial request was the only place with a false argument like `refreshPushStatus(publishChange: false)`.
So I've removed the `publishChange` parameter in favour of calculating a `shouldPublish` property that confirms that the value has changed AND (new) that there's an active session (this means that the previous value was used).
I've also added the same check to `setPushToken` so we're not …
> Ensure latest device prop values are always sent

- Sources/AppcuesKit/Push/PushAutoConfig.swift
- Sources/AppcuesKit/Push/UNUserNotificationCenter+AutoConfig.swift
Was working on push docs and noticed a two gaps in how the automatic push configuration calls completion handlers. For context:
[Docs](https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/usernotificationcenter(_:didreceive:withcompletionhandler:)) for `userNotificationCenter(_:didReceive:withCompletionHandler:)`:
> You must execute this block at some point after processing the user’s response to let the system know that you are done.
Docs for `userNotificationCenter(_:willPresent:withCompletionHandler:`:
> Always execute this block at some point during your implementation of this method.
First off, in `PushAutoConfig`, the completion handler wasn't being called in the case where there's not an Appcues instance to immediately handle the push, but we …
> Ensure push completion handlers are always called

- Sources/AppcuesKit/Presentation/Actions/Appcues/AppcuesLinkAction.swift
- Sources/AppcuesKit/Presentation/Extensions/UIApplication+TopViewController.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesEffectsTrait.swift
- Tests/AppcuesKitTests/Actions/AppcuesLinkActionTests.swift
- Tests/AppcuesKitTests/Networking/QualifyResponseDecodeTests.swift
As noted in #549, there's a compile error for Xcode 16/iOS 18 caused by the addition of `@MainActor @Sendable` to `UIApplication.open(_:options:completionHandler:)`. To maintain backwards compatibility I've added a different function to the protocol and then called `UIApplication.open` instead of updating the protocol to include `@MainActor @Sendable`.
Also updated tests to pass.
We still need to complete a wider audit of things on iOS 18 to ensure there's no issues, but this ensures teams aren't blocked by a compile error.
> Ensure Xcode 16/iOS 18 compiles

- Sources/AppcuesKit/Appcues.swift
Removing deprecated anonymous call as part of sdk4 breaking changes
> 💥 Removing deprecated anonymous call

- Sources/AppcuesKit/Appcues+Config.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceRenderer.swift
- Tests/AppcuesKitTests/PublicAPITests.swift
Setting this config to false will disable swizzling of UIScrollView but also disable our ability to show tooltips below the fold as the user scrolls
> Add configuration option for step recovery observer

- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesSkippableTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/ExperienceWrapperViewController+DragDirection.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/ExperienceWrapperViewController.swift
The idea here is to allow slideouts to swipe-to-dismiss similar to how a cover/half sheet would. That means a few things:
1. Only allowed when `isModalInPresentation == false`. This is controlled by the skippable trait. Otherwise the view can be dragged a bit, but rubber-bands back to the original position.
2. The view can be dragged in the dismissal direction (down for a sheet, to an adjacent edge for a slideout). Dragging otherwise (up for a sheet, towards non-adjacent edges for a slideout) will respond, but with a rubber-band effect to indicate it's being dragged in an unsupported direction.
3. The drag gestures are appropriately responsive, smooth, and feel "right".
Nothing here is too complicated. Process is as follows:
1. On presenting the modal, figure out which edges are allowed …
> Add support for swipe-to-dismiss of slideouts

- Sources/AppcuesKit/Presentation/ExperienceRendering/ModalContextManager.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesModalTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesTooltipTrait.swift
The `@appcues/modal` and `@appcues/tooltip` trait now present via the new `ModalContextManager` which manages the lifecycle of a `UIWindow` that's overlaid over the application to present modals and tooltips. This PR sets the foundation for the backdrop passthrough logic that's up next.
1. I created `ModalContextManager` to avoid having the exact same code in both the modal and tooltip traits. 
2. I considered having `ModalContextManager` only create a single window for the whole `Appcues` instance, but then ownership gets complicated and it's the job of the state machine anyways to make sure there's not multiple modals being presented.
3. There's an exception `useSameWindow: false` for the sheet modals that uses the old approach to preserve the scale animation of the presenting view …
> Update modal context traits to present in their own UIWindow

- Examples/DeveloperCocoapodsExample/CocoapodsExample/Base.lproj/Main.storyboard
- Sources/AppcuesKit/Presentation/Extensions/FrameObserverView.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesBackdropTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesEffectsTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesTargetInteractionTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/ExperienceWrapperView.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/ExperienceWrapperViewController+DragDirection.swift
Here's the idea:
1. The `ExperienceWrapperView` becomes a `HitTestingOverrideUIView(overrideApproach: .ignoreSelf)` so only hits in it's content are captured
2. The `ExperienceWrapperView.backdropView` also becomes a `HitTestingOverrideUIView(overrideApproach: .ignoreSelf)` so it doesn't capture any hits unless it has subviews that do.
3. We update the `AppcuesBackdropDecoratingTrait` to make sure they use subviews that do/don't capture hits as desired
1. `@appcues/backdrop` adds a subview now (instead of setting the color directly) that **does** capture hits
2. `@appcues/effects` does `effectView.isUserInteractionEnabled` so it **does not** capture hits (note that we can still have effects without a backdrop and in that case the user can interact with the app under the confetti)
3. …
> Ignore touches on backdrop with no traits

- Sources/AppcuesKit/Data/Analytics/AutoPropertyDecorator.swift
- Tests/AppcuesKitTests/Analytics/AutoPropertyDecoratorTests.swift
Will help support options in the future to only send push notifications within certain time windows in the device's timezone. This property is set at the user level (last known value) and each device level.
> Add _timezoneOffset auto property

- Sources/AppcuesKit/Presentation/Public/Plugins/AppcuesTraitMetadata.swift
- Sources/AppcuesKit/Presentation/Public/UIWindow+Appcues.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesTargetInteractionTrait.swift
A couple little tweaks in the wake of the UIWindow (#566) and backdrop (#567) changes. I haven't seen these impact 4.1.0, but they're things that could potentially cause unexpected behaviours.
1. The `isAppcuesWindow` check now also catches the `ModalContextManager.AppcuesUIWindow`. This could matter when determining the window to screen capture. It's unlikely to actually matter because "array orders the windows from back to front by window level" ([ref](https://developer.apple.com/documentation/uikit/uiapplication/1623104-windows#discussion)), and screen capture looks for the first non-appcues window, but good to be safe here.
2. Doing `metadata["backdropBackgroundColor"] != nil` isn't quite doing what you'd expect because of the generic <T> casting, so I added a `metadata[isSet:]` …
> Small window edge case enhancements

- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesTargetInteractionTrait.swift
Add support for interacting with the app through the tooltip target keyhole. I explored a lot of different approaches here and settled on this because:
1. it works
2. it's less likely to interfere with the customer's app or impact performance (no swizzling)
3. it requires no configuration (some delegate or custom window approach)
4. it should work x-plat (need to test and confirm)
5. it's all isolated in the target interaction trait where it belongs and is simple enough to understand
1. We override the `hitTest` in the `TargetView` created by the `@appcues/target-interaction` trait to
1. find the view in the app window that will be hit
2. attach a tap gesture recognizer to that view with `cancelsTouchesInView = false` (`cancelsTouchesInView` is the key to ensure the app still does the …
> Add support for @appcues/target-interaction pass through

- Examples/DeveloperCocoapodsExample/AppcuesCocoapodsExample.xcodeproj/project.pbxproj
- Examples/DeveloperCocoapodsExample/AppcuesCocoapodsExample.xcodeproj/xcshareddata/xcschemes/AppcuesCocoapodsExample.xcscheme
- Examples/DeveloperCocoapodsExample/project.yml
- Examples/DeveloperSPMExample/project.yml
- Sources/AppcuesKit/Presentation/Debugger/PushVerifier.swift
At some point `xcodegen` stopped generating a scheme for the example apps. It wasn't the end of the world to add it manually, but it's annoying and now it's fixed.
There's also an iOS 12+ deprecation warning in the `PushVerifier` that I've fixed up.
> Fix example project generation and deprecation warning

- Sources/AppcuesKit/Presentation/Actions/Appcues/AppcuesRequestReviewAction.swift
- Sources/AppcuesKit/Presentation/Debugger/UIDebugger.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ModalContextManager.swift
- Sources/AppcuesKit/Presentation/Extensions/UIApplication+TopViewController.swift
Two separate issues here, both related to the `UIWindow` presentation changes.
1. There's a case where an experience being presented while the app is closing (think event triggered experience on an open URL in external browser button tap) doesn't show because there's no _active_ window scene. If there's an active scene, we want to use it, but if there's not, we can fallback to the window scene for whatever the main app window is. This is essential the same check we use [here](https://github.com/appcues/appcues-ios-sdk/blob/ae53fa37e66ca44e5777542a5783749db753fc04/Sources/AppcuesKit/Presentation/Extensions/UIApplication%2BTopViewController.swift#L58-L60) for the computation of `UIApplication.topViewController()` as used by the sheet presentation styles. I've updated all the places that …
> AppcuesUIWindow fixes

- .circleci/config.yml
- Sources/AppcuesKit/Appcues.swift
- Sources/AppcuesKit/Data/Analytics/UIKitScreenTracker.swift
- Sources/AppcuesKit/Data/Extensions/NotificationCenter+Custom.swift
- Sources/AppcuesKit/Data/Extensions/UUID+Custom.swift
- Sources/AppcuesKit/Data/Models/Experience/StepReference.swift
- Sources/AppcuesKit/Data/Models/SdkMetrics.swift
- Sources/AppcuesKit/Presentation/Debugger/FloatingView/DebugView.swift
- Sources/AppcuesKit/Presentation/Debugger/FloatingView/FleetingLogView.swift
- Sources/AppcuesKit/Presentation/Debugger/Toasts/ToastUIWindow.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/Dictionary+ExperienceProperties.swift
- Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateObserver.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesBackdropTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesEffectsTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesSkippableTrait.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesStepTransitionAnimationTrait.swift
- Sources/AppcuesKit/Presentation/Traits/TraitComposer.swift
- Sources/AppcuesKit/Presentation/UI/Components/EnvironmentValues+ImageCache.swift
- Sources/AppcuesKit/Presentation/UI/ExperienceStepViewController.swift
- Sources/AppcuesKit/Push/UNUserNotificationCenter+AutoConfig.swift
- Tests/AppcuesKitTests/Analytics/AnalyticsTrackerTests.swift
- Tests/AppcuesKitTests/Experiences/ExperienceStateMachine+AnalyticsObserverTests.swift
This is tackling some of the low hanging fruit of warnings on the road to Swift 6.
1. `scrollIndicatorInsets` was deprecated.
2. Using a `Timer` causes isolation warnings, so I replaced those with Tasks that sleep. Good article here: https://wadetregaskis.com/performing-a-delayed-and-or-repeating-operation-in-a-swift-actor/
3. Fixed the easy isolated global variable warnings by changing `static var` to static let` and adding `nonisolated(unsafe)` where it makes sense. There are still other instances of this warning that will be a bit more work to resolve.
> Concurrency warning fixes

- Sources/AppcuesKit/Data/Analytics/AnalyticsPublisher.swift
- Sources/AppcuesKit/Push/PushMonitor.swift
`AnalyticsPublisher` has some thread safety issues. Our sdk5 work should address the root of these, but for now, we need some patches. This PR does two things:
1. Updates PushMonitor to track new status on main thread. I believe the cause of new thread safety issues is the device updated event coming through at startup on an arbitrary thread.
2. Removing the `removeAll` in `AnalyticsPublisher` to avoid mutating the array in an unsafe way. This was here to clean up any `WeakAnalytic*` instances whose weak references has been de-inited. However, in practice this doesn't need to happen since there's a single decorator (`AutoPropertyDecorator`) and 3 subscribers (`AnalyticsTracker`, `AnalyticsBroadcaster` and `UIDebugger`). The weak references are still necessary for the SDK to be able to …
> Address potential crashes in AnalyticsPublisher

- Sources/AppcuesKit/Presentation/Extensions/UIScrollView+ScrollObserver.swift
This should ensure we don't accidentally call an `unrecognized selector`. I haven't been able to reproduce such a scenario to test so this is a bit speculative, but it won't hurt.
> Verify selector before calling swizzled implementation

- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/Capture.swift
- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/UIKitElementTargeting.swift
- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/UIView+Capture.swift
- Sources/AppcuesKit/Presentation/Debugger/UIDebugger.swift
- Sources/AppcuesKit/Presentation/Extensions/UIApplication+TopViewController.swift
- Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesTargetInteractionTrait.swift
1. I've modernized the screen capture and annotation to use `UIGraphicsImageRenderer`. I've also added a check for a zero-sized capture, so now we show an error toast instead of crashing or having a confusing blank confirm screen.
2. To try and avoid getting the zero-sized capture failure, I've reworked and consolidated the scene/window logic to avoid a window with a zero-frame. I'm still not sure how it's possible, but if it is, we'll ignore a window like that in preference of another one.
We had a couple different ways of finding the "main" window:
1. The `topViewController()` implementation would try and find the `keyWindow`, with a fallback in case the `keyWindow` was an appcues window.
2. Everything else (screen capture, element targeting) would look through all windows and take the …
> Screen capture flow improvements

- Sources/AppcuesKit/Presentation/Extensions/UIScrollView+ScrollObserver.swift
- Tests/AppcuesKitTests/SwizzlerTests.swift
We discovered that scroll view swizzling can interfere with React Native multiline `TextInput` components (that use `UITextView` under the hood). The delegate setter for `RCTUITextView` checks to ensure the current delegate is `nil` before setting the delegate value which is needed to handle the input events ([ref](https://github.com/facebook/react-native/blob/f53d066d26352e6abfdf2f727ea06425ea163039/packages/react-native/Libraries/Text/TextInput/Multiline/RCTUITextView.mm#L69-L71)). The `StepRecoveryObserver` scroll view swizzling meant that the delegate value was an `AppcuesScrollViewDelegate` instead of `nil`.
There's no reason for us to care about scrolling in a `UITextView`, since there's not going to be a "below the fold" target element inside a text view, so we can return early the …
> Exclude UITextView from step recovery UIScrollView swizzling

- Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/UIKitElementTargeting.swift
Fixes found while implementing https://github.com/appcues/appcues-react-native-module/pull/194
1. Calculate proper offset in case the web view isn't at (0, 0)
2. Ensure web view elements outside the webview frame are ignored
> Web view targeting fixes

- Sources/AppcuesKit/Data/Models/Clause.swift
- Tests/AppcuesKitTests/Experiences/ClauseTests.swift
We've redefined the expected behavior of for incomplete/malformed clauses. Previously we'd fallback to `unknown` for unknown clause types, but now we also do if a known clause is malformed.
The reason for this is that it's possible to have an incomplete state in the mobile builder and we want to handle that as graciously as possible (imagine 4 valid checks and one incomplete one at the end: we can now properly handle the first 4 cases instead of failing entirely to decode the config).
We do still want to throw errors for very wrong data (ie we don't want any random JSON to decode to `unknown` since that's not helpful at all), so the key count still throws as does decoding clause groups since we'll have stricter control over how those are structured.
> Update clause decoding behavior
