appcues/appcues-ios-sdk

Sources/AppcuesKit/Presentation/Debugger/UIDebugger.swift, Sources/AppcuesKit/Presentation/DeeplinkHandler.swift
React Native can call these from background threads.
=> Thread safety improvements

Sources/AppcuesKit/AppcuesKit.docc/AnalyticObserving.md, Sources/AppcuesKit/AppcuesKit.docc/AppcuesKit.md
=> Add documentation for usage of AppcuesAnalyticsDelegate

Sources/AppcuesKit/Appcues.swift
Just one minor change needed that is technically more correct on older versions as well, from what I understand based on posts here https://stackoverflow.com/a/51250282
=> Add support for compiling on XCode 14

README.md
Will merge this and then run the `1.0.0.beta.4` release right after so that it's actually correct.
=> Add beta-specific install notes to README

.swiftlint.yml, Examples/DeveloperCocoapodsExample/CocoapodsExample/AppDelegate.swift, Examples/DeveloperCocoapodsExample/CocoapodsExample/DeeplinkNavigator.swift, Examples/DeveloperCocoapodsExample/CocoapodsExample/SceneDelegate.swift, Examples/DeveloperCocoapodsExample/Podfile.lock, Examples/DeveloperCocoapodsExample/README.md, Examples/DeveloperObjcExample/ObjcExample/SceneDelegate.m, Examples/DeveloperSPMExample/AppcuesSPMExample.xcodeproj/project.pbxproj, Examples/DeveloperSPMExample/README.md, Examples/DeveloperSPMExample/SPMExample/AppDelegate.swift, Examples/DeveloperSPMExample/SPMExample/DeeplinkNavigator.swift, Examples/DeveloperSPMExample/SPMExample/SceneDelegate.swift, Sources/AppcuesKit/Appcues.swift, Sources/AppcuesKit/AppcuesKit.docc/Debugging.md, Sources/AppcuesKit/AppcuesKit.docc/URLSchemeConfiguring.md, Sources/AppcuesKit/Presentation/Debugger/Panel/DebugViewModel.swift, Sources/AppcuesKit/Presentation/DeeplinkHandler.swift, Tests/AppcuesKitTests/AppcuesTests.swift, Tests/AppcuesKitTests/DeeplinkHandlerTests.swift, Tests/AppcuesKitTests/MockAppcues.swift
A truly vital PR...
I created a lint rule that will remind us to be consistent in the future:
=> Deep link spelling

Sources/AppcuesKit/Appcues.swift
I was doing some copy/paste/editing from docs here to the Flutter plugin to finish that out, and noticed a few small tweaks I wanted to propose here.
=> Update public interface docs

Sources/AppcuesKit/Presentation/UI/Components/AppcuesButton.swift
Explanation is commented in the code.
Tests are in the spec repo: https://github.com/appcues/appcues-mobile-experience-spec/pull/75
=> Fix content alignment not applied within button views

Sources/AppcuesKit/Data/Analytics/AnalyticsTracker.swift, Sources/AppcuesKit/Presentation/Actions/Appcues/AppcuesStepInteractionAction.swift, Sources/AppcuesKit/Presentation/ExperienceRendering/LifecycleEvent.swift
I noticed I accidentally introduced one in a recent commit. There were also a couple other simple line length items - cleaned up.
=> Fix some SwiftLint warnings

Sources/AppcuesKit/Data/Models/Experience/ExperienceComponent.swift, Sources/AppcuesKit/Presentation/UI/ExperienceData.swift, Tests/AppcuesKitTests/Experiences/ExperienceDataTests.swift
An alternative approach to #298
=> Add leadingFill option for rating components

Sources/AppcuesKit/Presentation/Extensions/View+Appcues.swift, Sources/AppcuesKit/Presentation/UI/Components/AppcuesButton.swift, Sources/AppcuesKit/Presentation/UI/Components/AppcuesImage.swift
Making a correction from issue noted in this comment https://github.com/appcues/appcues-mobile-experience-spec/pull/123#issuecomment-1359833175
Fix validated in this commit https://github.com/appcues/appcues-mobile-experience-spec/pull/123/commits/207b4ab8aaba825376c595169dc36b78f6455956
=> Apply border, background, cornerRadius and shadow in that order

.swiftlint.yml, Sources/AppcuesKit/Data/Models/Experience/ExperienceComponent.swift, Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/Capture.swift, Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesTargetRectangleTrait.swift
follow up item from https://github.com/appcues/appcues-ios-sdk/pull/313#discussion_r1072605331
=> Update SwiftLint identifier_name rule to allow x and y

Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesTargetElementTrait.swift
The target element equivalent of #320
=> Fix double publishing of target element frame

Sources/AppcuesKit/Vendor/FLAnimatedImage.swift
`maxOptimalSize` is the frame count that we buffer for an animated gif. Previously we'd compute the size of _all the frames in an image_ (`animatedImageDataSize`) to determine the cache size. That makes sense for the `if` condition where we check if the all the frames in the image should be cached.
That makes no sense for the subsequent `else if` check because the total number of frames in the gif is unrelated to the size of a single frame. I've updated it to determine how many frames we can cache while staying under the max cache size.
I've also updated that max size from 10MB to 15MB.
The result is this (a cache size of >1  should result in stutter-free playback, but a larger cache is safer)
|Image Resolution|Frame Count|Old Cached Frame Count|New Cached Frame Count|
|-|-|-|-| …
=> Update animated GIF buffer calculation to allow larger caches

Sources/AppcuesKit/Presentation/Actions/ActionRegistry.swift, Sources/AppcuesKit/Presentation/Actions/Appcues/AppcuesRequestReviewAction.swift
Brings back what was added in #174 then removed in #230
=> Add @appcues/request-review action

Sources/AppcuesKit/Presentation/Traits/Appcues/DialogContainerViewController.swift, Sources/AppcuesKit/Presentation/UI/ExperienceStepViewController.swift
This approach preserves the "scroll to visible" approach if the bottom aligned modal is tall enough, otherwise it shifts the whole modal up to ensure the content is visible.
Animation for the shift on the short modal isn't included because the shadow doesn't properly animate. This will be fixed in the future.
https://user-images.githubusercontent.com/845681/224135151-c8ec12f7-17eb-45c3-b35f-0dd48df8861a.mp4
https://user-images.githubusercontent.com/845681/224135170-24141b21-d45c-4db5-8ed1-e6a08225fa0d.mp4
=> Fix keyboard avoidance for small bottom-aligned modals

release.sh
A hidden `<fe0f>` was filtering out some emoji we want to include.
=> 🔧 Update release changelog emoji exclusion

Sources/AppcuesKit/Presentation/Extensions/UIBezierPath+Tooltip.swift, Sources/AppcuesKit/Presentation/Traits/Appcues/TooltipWrapperView.swift, Tests/AppcuesKitTests/Experiences/TooltipWrapperViewFrameTests.swift
- appcues/appcues-mobile-experience-spec#162
=> Update tooltip positioning to use left/right

Sources/AppcuesKit/Presentation/Extensions/HitTestingOverrideUIView.swift, Sources/AppcuesKit/Presentation/Traits/Appcues/ExperienceWrapperView.swift, Sources/AppcuesKit/Presentation/Traits/Appcues/TooltipWrapperView.swift
Take a look at each individual commit
=> 3 little tooltip UI fixes

Sources/AppcuesKit/Presentation/Extensions/CGSize+PointerSize.swift, Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesSkippableTrait.swift
Also sneaking in an update to the pointer corner radius comments.
=> Add button styling options to @appcues/skippable

Sources/AppcuesKit/AppcuesKit.docc/Traits.md
Clarification found in review of Android doc here https://github.com/appcues/appcues-android-sdk/pull/386#discussion_r1176456071
=> Fix note about multiple trait types at the same level

Examples/DeveloperCocoapodsExample/Podfile.lock, Gemfile, Gemfile.lock
Updating example app just to be in sync with other projects (Flutter and Ionic required the update for Xcode 14.3)
=> Update to Cocoapods 1.12.1

Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesBackdropKeyholeTrait.swift
> Gradient with locations close to 1.0 was failing to transition fully to the expected color. Doubling the size of the gradient and then moving the location stops to 0.5 fixes this.
For a circular keyhole with no `spreadRadius` we were still doing a tiny gradient (this enables animation between `spreadRadius` values), but the gradient stop position values are so close together at the edge of the gradient (0.995 and 1.0) it’s not getting all the way to the full opacity mask and the result is a lighter backdrop color than expected.
The solution here is to move the gradient stop positions to 50% (ie color locations at 0.4999995, 0.5), so I adjusted the gradient to be double the size but then have the locations at the 50% point instead of 100%.
Snapshot tests in …
=> Fix incorrect color on backdrop with circular keyhole

README.md
Merge this right before we release a stable version `2.0.0`.
=> Update major version in README

Sources/AppcuesKit/AppcuesKit.docc/2.0MigrationGuide.md
This is a requested change from Chris, to lead with the positive/common case first.
=> Update the introduction for 2.0 migration doc

Sources/AppcuesKit/Presentation/ExperienceRendering/StateMachineDirectory.swift, Tests/AppcuesKitTests/Experiences/ExperienceRendererTests.swift
A pretty standard implementation to make sure that reads and writes to the `stateMachines` dictionary are thread safe.
=> Update StateMachineDirectory to be thread safe

Sources/AppcuesKit/Presentation/Debugger/Panel/DebugViewModel.swift, Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceRenderer.swift, Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateMachine.swift, Sources/AppcuesKit/Presentation/ExperienceRendering/LifecycleEvent.swift, Sources/AppcuesKit/Presentation/UI/AppcuesFrameView.swift, Tests/AppcuesKitTests/Experiences/EmbedExperienceRendererTests.swift
3 little things:
1.  Transition frame state machine to idling instead of setting to nil
2. Fixing the fade animation
3. Include frameID in debugger experience list
=> Embed polishing

.circleci/config.yml
Using a project specific variable to not conflict with the one defined in the org context.
=> Update the Codecov token variable to match CircleCI

README.md, Sources/AppcuesKit/AppcuesKit.docc/GettingStarted.md, fastlane/docs.sh
Sam/Paige [noted](https://appcues.slack.com/archives/C02EX9N4067/p1694119541644009) that the Getting Started guide was missing references to our newer features.
=> Update getting started docs to include new features

Sources/AppcuesKit/Data/Analytics/AutoPropertyDecorator.swift, Sources/AppcuesKit/Data/Models/Experience.swift, Sources/AppcuesKit/Presentation/Debugger/FloatingView/DebugView.swift, Sources/AppcuesKit/Presentation/Debugger/FloatingView/FleetingItemView.swift, Sources/AppcuesKit/Presentation/Debugger/FloatingView/FleetingLogView.swift, Sources/AppcuesKit/Presentation/Debugger/Panel/DebugUI.swift, Sources/AppcuesKit/Presentation/ExperienceRendering/LifecycleEvent.swift, Tests/AppcuesKitTests/Actions/AppcuesStepInteractionActionTests.swift, Tests/AppcuesKitTests/Analytics/ActivityProcessorTests.swift, Tests/AppcuesKitTests/Analytics/SdkMetricsTests.swift, Tests/AppcuesKitTests/Experiences/EmbedExperienceRendererTests.swift, Tests/AppcuesKitTests/Experiences/ExperienceStateMachine+AnalyticsObserverTests.swift, Tests/AppcuesKitTests/Experiences/ExperienceStateMachineTests.swift, Tests/AppcuesKitTests/Mocks.swift, Tests/AppcuesKitTests/Traits/TraitComposerTests.swift
1. Fix the debugger to always be LTR since it's always in English
2. Update the `_lastBrowserLanguage` auto property to use the bundle value
3. Add `localeId` and `localeName` to experience analytics if the `context` values are provided
=> Localization enhancements

Sources/AppcuesKit/Presentation/Debugger/Panel/DebugUI.swift, Sources/AppcuesKit/Presentation/Debugger/Panel/DebugViewModel.swift
|With group|Without group|
|-|-|
|![Simulator Screenshot - iPhone 14 Pro - 2023-11-13 at 10 20 57](https://github.com/appcues/appcues-ios-sdk/assets/845681/57afdbeb-51db-46c4-8bb4-87f04620fa72)|![Simulator Screenshot - iPhone 14 Pro - 2023-11-13 at 10 20 40](https://github.com/appcues/appcues-ios-sdk/assets/845681/872ca9d1-c235-455d-92f4-e2d042f2e1b4)|
=> Add group status row to debugger

Examples/DeveloperCocoapodsExample/AppcuesCocoapodsExample.xcodeproj/project.pbxproj, Examples/DeveloperCocoapodsExample/CocoapodsExample/Base.lproj/Main.storyboard, Examples/DeveloperCocoapodsExample/CocoapodsExample/ScrollingTableViewController.swift, Examples/DeveloperCocoapodsExample/Podfile.lock, Examples/DeveloperSPMExample/AppcuesSPMExample.xcodeproj/project.pbxproj, Examples/DeveloperSPMExample/SPMExample/Base.lproj/Main.storyboard, Examples/DeveloperSPMExample/SPMExample/ScrollingTableViewController.swift
Contains targetable buttons, button1…button5
=> Add scrolling content to example apps

Sources/AppcuesKit/Presentation/Debugger/FloatingView/DebugViewController.swift, Sources/AppcuesKit/Presentation/Debugger/UIDebugger.swift
This allows the debugger to inspect the screen capture flow network requests, which will make troubleshooting that flow much easier. Added bonus is that `UIDebugger.show(mode:)` is now simpler overall!
Instead of calling `hide()` and tearing down and recreating the debug panel and data when the mode changes, we preserve it, which means we can capture the data flow through the screen capture process. A few changes were needed in `DebugViewController` to allow `mode` to be changed and update the view to reflect the new mode instead of just being a `let` constant that is configured at init.
=> Preserve debug data through debugger mode changes

Sources/AppcuesKit/Presentation/Actions/Appcues/AppcuesTrackAction.swift
fix decoding here so the attribute values in the experience JSON make it all the way through
related to https://github.com/appcues/appcues-ios-sdk/pull/488
=> Fix decoding of track event additional attributes

.circleci/config.yml, fastlane/Fastfile
Also added a parallel job to run during branch validation to confirm the example apps compile - runs in parallel to the tests being executed in the spec repo.
=> Update sample app build to use Xcode 15.1

Sources/AppcuesKit/Data/Analytics/AnalyticsTracker.swift, Sources/AppcuesKit/Data/Analytics/AutoPropertyDecorator.swift, Sources/AppcuesKit/Data/Networking/DynamicCodingKeys.swift, Sources/AppcuesKit/Presentation/Debugger/Panel/LoggedEvent.swift, Tests/AppcuesKitTests/Analytics/AutoPropertyDecoratorTests.swift
Did a bit of cleanup and then added the initial `_device` structure. Also updated the debugger to show `_device` as a standalone section.
=> Add _device auto properties

Sources/AppcuesKit/Appcues.swift, Sources/AppcuesKit/Data/Analytics/AutoPropertyDecorator.swift, Sources/AppcuesKit/Data/Events.swift, Sources/AppcuesKit/Presentation/Debugger/Panel/LoggedEvent.swift, Tests/AppcuesKitTests/AppcuesTests.swift
New device events for when the push token changes or the user is reset.
Also [sc-62374]
=> Add device events

Sources/AppcuesKit/Data/Analytics/AutoPropertyDecorator.swift, Sources/AppcuesKit/Data/PushMonitor.swift, Sources/AppcuesKit/Presentation/Actions/Appcues/AppcuesRequestPushAction.swift, Tests/AppcuesKitTests/Actions/AppcuesRequestPushActionTests.swift, Tests/AppcuesKitTests/Analytics/AutoPropertyDecoratorTests.swift, Tests/AppcuesKitTests/MockAppcues.swift, Tests/AppcuesKitTests/PushMonitorTests.swift
New `_pushPrimerEligible` auto prop and `@appcues/request-push` action.
Also [sc-60936]
=> Add push primer support

Sources/AppcuesKit/Presentation/Debugger/ScreenCapturing/ScreenCapturer.swift, Sources/AppcuesKit/Presentation/Debugger/Toasts/DebugToast.swift, Sources/AppcuesKit/Presentation/Debugger/Toasts/ToastView.swift
=> Add new screen capture error message for expired tokens

Sources/AppcuesKit/Data/Models/Event.swift, Sources/AppcuesKit/Presentation/Actions/Appcues/AppcuesStepInteractionAction.swift, Sources/AppcuesKit/Presentation/Debugger/DebugLogger.swift, Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateObserver.swift, Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesCarouselTrait.swift, Sources/AppcuesKit/Presentation/UI/AppcuesFrame.swift, Sources/AppcuesKit/Presentation/UI/Components/AppcuesOptionSelect.swift
=> Fix lint warnings

Sources/AppcuesKit/Presentation/Debugger/PushVerifier.swift
As [suggested](https://github.com/appcues/appcues-ios-sdk/pull/514#pullrequestreview-1932057748)
|No `willPresent` implemented|`.banner` not included in options|Note + error|
|-|-|-|
|![Simulator Screenshot - iPhone 15 Pro - 2024-03-13 at 11 27 21](https://github.com/appcues/appcues-ios-sdk/assets/845681/170eabd2-2d95-4807-9c90-02dcc4e7c8ae)|![Simulator Screenshot - iPhone 15 Pro - 2024-03-13 at 11 27 07](https://github.com/appcues/appcues-ios-sdk/assets/845681/1b8121f7-7e0d-4087-8520-6b1cfa9e0727)|![Simulator Screenshot - iPhone 15 Pro - 2024-03-13 at 11 27 45](https://github.com/appcues/appcues-ios-sdk/assets/845681/253bee09-9273-402f-b60e-0fc70514349a)|
=> Add foreground hander verification to PushVerifier

Sources/AppcuesKit/Push/ParsedNotification.swift, Sources/AppcuesKit/Push/PushMonitor.swift, Tests/AppcuesKitTests/Push/PushMonitorTests.swift
Adding `app_id` and removing `transaction_id`
=> Push updates

Sources/AppcuesKit/Push/PushAutoConfig.swift
This PR adds automatic push config support for `Appcues` instances created after `Appcues.enableAutomaticPushConfig()` is called. `enableAutomaticPushConfig()` must be called from `didFinishLaunchingWithOptions`, but the `Appcues` instance might not be inited until after (especially in the case of Democues!)
There's 2 things to handle:
1. The push token. We save the most recent value and give it to the new instance when it's registered.
2. A notification response. If the notification response was handled by an existing instance, we can ignore it, but otherwise save the most recent one for a new instance to try and handle.
The end result is that in Democues, a notification can (cold) launch the app, and once a matching account ID and app ID are entered (which creates the `Appcues` …
=> Update push auto config to store values for future instances

AppcuesNotificationService.podspec, release.sh
Need to
1. Update the version number (I've set it to `4.0.0-alpha.1` preemptively this time, but we'll need it in the future)
2. Publish the pod
=> Update release script for AppcuesNotificationService

Sources/AppcuesKit/Presentation/Actions/ActionRegistry.swift, Sources/AppcuesKit/Presentation/Actions/Appcues/AppcuesDelayAction.swift, Tests/AppcuesKitTests/Actions/AppcuesDelayActionTests.swift
Very basic: just wait for the designated amount of time and the complete.
=> Add @appcues/delay action

Sources/AppcuesKit/Presentation/Traits/Appcues/AppcuesEffectsTrait.swift, Sources/AppcuesKit/Presentation/Traits/TraitRegistry.swift
There's a few default values:
- `2000ms` duration
- `1` intensity
- `["#5C5CFF", "#20E0D6", "#FF5290"]` default colors if no `style.colors`
cc @FredericoVieira @andretortolano
=> Add @appcues/effects trait

README.md
Note the link doesn't work yet since we haven't published the docs since all the releases have been pre-releases.
=> Add link to push docs from README

Sources/AppcuesKit/Presentation/UI/Components/AppcuesImage.swift
Image urls in the builder changed for new experiences:
```
OLD: https://res.cloudinary.com/xyz/image/upload/v123/000/abc.svg
NEW: https://images.appcues.com/image/upload/v123/000/abc.svg
```
I've updated our SVG->PNG code to support both url formats.
=> Update svg mapping to support new image domain

Sources/AppcuesKit/Push/PushMonitor.swift, Tests/AppcuesKitTests/Push/PushMonitorTests.swift
=> Update push analytic property names

Sources/AppcuesKit/Push/UNUserNotificationCenter+AutoConfig.swift
It was possible to get stuck in an infinite loop and crash at startup when using `Appcues.enableAutomaticPushConfig()`.
This is an alternate solution to the one suggested in #578. The benefit of this approach is primarily consistency—it's the same solution that we used for `UIScrollViewDelegate` swizzling ([ref](https://github.com/appcues/appcues-ios-sdk/blob/b1dc1a4300b87cdeca08e9d60083015d73165c1b/Sources/AppcuesKit/Presentation/Extensions/UIScrollView%2BScrollObserver.swift#L96))
The crash can be reproduced and tested with an Expo app that uses [`@react-native-firebase/messaging`](https://rnfirebase.io/messaging/usage).
=> Fix crash when swizzling for push auto config

Sources/AppcuesKit/Data/Analytics/AutoPropertyDecorator.swift, Tests/AppcuesKitTests/Analytics/AutoPropertyDecoratorTests.swift
=> Add _timezoneCode auto property

Sources/AppcuesKit/Appcues.swift, Tests/AppcuesKitTests/AppcuesTests.swift
iOS version of
- https://github.com/appcues/appcues-android-sdk/pull/661
=> Do not allow tracking empty event names
